import React, { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../context/AuthContext';
import { callApi } from '../../services/api';
import { Loading, ErrorState } from '../../components/ui/StateIndicator';
import { 
  Plus, 
  Search,
  X,
  MessageCircle,
  CheckCircle2,
  AlertCircle,
  ShieldCheck,
  RotateCcw,
  Send,
  Trash2,
  Layers,
  Users2,
  Sliders,
  ExternalLink
} from 'lucide-react';

export interface DepartmentAssignment {
  teamId: string;
  teamName?: string;
  assignedTo: string;
  assigneeName?: string;
  status: 'NOT_STARTED' | 'IN_PROGRESS' | 'VERIFY' | 'COMPLETED' | 'BLOCKED' | string;
  progress: number;
  remarks?: string;
  lastUpdated?: string;
}

export interface Task {
  taskId: string;
  eventId: string;
  projectId: string;
  taskTitle: string;
  taskDescription: string;
  teamId: string;
  assignedTo: string;
  assignedBy: string;
  verifierId?: string;
  priority: string;
  startDate: string;
  deadline: string;
  status: string;
  completionPercent: number;
  departmentAssignments?: string | DepartmentAssignment[];
  remarks: string;
  rejectionRemarks?: string;
  completionDate: string;
  driveLink: string;
  isAutoGenerated: string;
}

interface Team {
  teamId: string;
  teamName: string;
  teamCode: string;
}

interface User {
  userId: string;
  name: string;
  email: string;
  role: string;
  teamId: string;
  position?: string;
  phone?: string;
}

interface EventItem {
  eventId: string;
  eventName: string;
  eventStatus?: string;
}

export function parseDepartmentAssignments(raw?: string | DepartmentAssignment[]): DepartmentAssignment[] {
  if (!raw) return [];
  if (Array.isArray(raw)) return raw;
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

const LANES = [
  { id: 'NOT_STARTED', title: 'Not Started', color: 'bg-slate-100 dark:bg-slate-900/40 text-slate-800 dark:text-slate-200 border-slate-200/50' },
  { id: 'IN_PROGRESS', title: 'In Progress', color: 'bg-blue-50/50 dark:bg-blue-950/20 text-blue-800 dark:text-blue-200 border-blue-200/40' },
  { id: 'VERIFY', title: 'Under Verification', color: 'bg-purple-50/50 dark:bg-purple-950/20 text-purple-800 dark:text-purple-200 border-purple-200/40' },
  { id: 'DELAYED', title: 'Delayed', color: 'bg-amber-50/50 dark:bg-amber-950/20 text-amber-800 dark:text-amber-200 border-amber-200/40' },
  { id: 'BLOCKED', title: 'Blocked', color: 'bg-red-50/50 dark:bg-red-950/20 text-red-800 dark:text-red-200 border-red-200/40' },
  { id: 'COMPLETED', title: 'Completed', color: 'bg-green-50/50 dark:bg-green-950/20 text-green-800 dark:text-green-200 border-green-200/40' },
];

export const TaskBoardPage: React.FC = () => {
  const { profile } = useAuth();
  const role = profile?.role || 'MEMBER';
  const myUserId = profile?.userId || '';
  const myTeamId = profile?.teamId || '';
  const queryClient = useQueryClient();

  // Selected Task for detailed view / edit
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);

  // Filters State
  const [filterTeam, setFilterTeam] = useState<string>('');
  const [filterAssignee, setFilterAssignee] = useState<string>('');
  const [filterEvent, setFilterEvent] = useState<string>('');
  const [filterPriority, setFilterPriority] = useState<string>('');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const handleWhatsAppReminder = (e: React.MouseEvent, t: Task) => {
    e.stopPropagation();
    const user = users.find(u => u.userId === t.assignedTo);
    if (!user) {
      alert("This task is not assigned to any user.");
      return;
    }
    const phone = user.phone ? user.phone.replace(/[^0-9]/g, '') : '';
    if (!phone) {
      const entered = window.prompt(`Enter WhatsApp phone number (with country code, e.g. 919988776655) for ${user.name}:`);
      if (entered) {
        launchWhatsApp(entered, user.name, t);
      }
    } else {
      launchWhatsApp(phone, user.name, t);
    }
  };

  const launchWhatsApp = (phone: string, userName: string, t: Task) => {
    const msg = `Hi ${userName}, just reminding you about your assigned task "${t.taskTitle}" on NEXUS. Priority: ${t.priority}, Deadline: ${t.deadline ? new Date(t.deadline).toLocaleDateString('en-IN') : 'N/A'}. Please update its status on the portal!`;
    const url = `https://api.whatsapp.com/send?phone=${phone}&text=${encodeURIComponent(msg)}`;
    window.open(url, '_blank');
  };

  // Fetch lists
  const { data: rawTasks = [], isLoading: tasksLoading, error: tasksError, refetch: refetchTasks } = useQuery<Task[]>({
    queryKey: ['tasks'],
    queryFn: () => callApi('tasks.list'),
  });

  const { data: teams = [] } = useQuery<Team[]>({
    queryKey: ['teams'],
    queryFn: () => callApi('teams.list'),
  });

  const { data: users = [] } = useQuery<User[]>({
    queryKey: ['users'],
    queryFn: () => callApi('users.list'),
  });

  const { data: rawEvents = [] } = useQuery<EventItem[]>({
    queryKey: ['events'],
    queryFn: () => callApi('events.list'),
  });

  const events = React.useMemo(() => {
    return rawEvents.filter(e => String(e.eventStatus || '').toUpperCase() !== 'CANCELLED');
  }, [rawEvents]);

  const activeEventsMap = React.useMemo(() => {
    const map = new Set<string>();
    events.forEach(e => map.add(e.eventId));
    return map;
  }, [events]);

  const tasks = React.useMemo(() => {
    return rawTasks.filter(t => {
      if (String(t.status || '').toUpperCase() === 'CANCELLED') return false;
      if (t.eventId && rawEvents.length > 0 && !activeEventsMap.has(t.eventId)) {
        return false;
      }
      return true;
    });
  }, [rawTasks, rawEvents, activeEventsMap]);

  // Direct URL Task Link Handler (?taskId=TSK-XXXX)
  useEffect(() => {
    if (tasks.length > 0) {
      const urlParams = new URLSearchParams(window.location.search);
      const directTaskId = urlParams.get('taskId');
      if (directTaskId) {
        const found = tasks.find(t => t.taskId === directTaskId);
        if (found) {
          setSelectedTask(found);
        }
      }
    }
  }, [tasks]);

  // Mutations
  const updateStatusMutation = useMutation({
    mutationFn: ({ taskId, status, remarks }: { taskId: string; status: string; remarks?: string }) =>
      callApi('tasks.updateStatus', { taskId, status, remarks: remarks || `Moved to ${status} via Kanban drag.` }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Update failed: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  const editTaskMutation = useMutation({
    mutationFn: ({ taskId, payload }: { taskId: string; payload: any }) =>
      callApi('tasks.update', { taskId, ...payload }),
    onSuccess: () => {
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Failed to save task: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  const createTaskMutation = useMutation({
    mutationFn: (newTaskPayload: any) =>
      callApi('tasks.create', newTaskPayload),
    onSuccess: () => {
      setIsCreateModalOpen(false);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Failed to create task: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  const submitVerificationMutation = useMutation({
    mutationFn: ({ taskId, remarks, verifierId }: { taskId: string; remarks?: string; verifierId?: string }) =>
      callApi('tasks.submitForVerification', { taskId, verifierId, remarks: remarks || 'Submitted for verification.' }),
    onSuccess: () => {
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Verification submission failed: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  const verifyMutation = useMutation({
    mutationFn: ({ taskId, remarks }: { taskId: string; remarks?: string }) =>
      callApi('tasks.verify', { taskId, remarks: remarks || 'Verified and approved.' }),
    onSuccess: () => {
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Approval failed: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  const rejectMutation = useMutation({
    mutationFn: ({ taskId, remarks }: { taskId: string; remarks: string }) =>
      callApi('tasks.reject', { taskId, remarks }),
    onSuccess: () => {
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Rejection failed: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  const deleteTaskMutation = useMutation({
    mutationFn: (taskId: string) => callApi('tasks.delete', { taskId }),
    onSuccess: () => {
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Failed to delete task: ${err instanceof Error ? err.message : 'Unauthorized action'}`);
    }
  });

  // Permissions helpers
  const canDeleteTask = (task: Task) => {
    if (role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN') return true;
    if (task.assignedBy && task.assignedBy === myUserId) return true;
    return false;
  };

  const canEditTask = (task: Task) => {
    if (role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN') return true;
    if (role === 'LEAD' && task.teamId === myTeamId) return true;
    if (task.assignedBy && task.assignedBy === myUserId) return true;
    if (task.assignedTo && task.assignedTo === myUserId) return true;
    
    // Multi-department sub-assignee check
    const subs = parseDepartmentAssignments(task.departmentAssignments);
    if (subs.some(s => s.assignedTo === myUserId || (role === 'LEAD' && s.teamId === myTeamId))) return true;
    
    return false;
  };

  const canEditAdminFields = (task: Task) => {
    if (role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN') return true;
    if (role === 'LEAD' && task.teamId === myTeamId) return true;
    if (task.assignedBy && task.assignedBy === myUserId) return true;
    return false;
  };

  const canVerifyTask = (task: Task) => {
    if (role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN') return true;
    if (role === 'LEAD' && task.teamId === myTeamId) return true;
    if (task.verifierId && task.verifierId === myUserId) return true;
    if (task.assignedBy && task.assignedBy === myUserId) return true;
    return false;
  };

  // Drag and Drop
  const handleDragStart = (e: React.DragEvent, task: Task) => {
    e.dataTransfer.setData('text/plain', task.taskId);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = (e: React.DragEvent, targetStatus: string) => {
    e.preventDefault();
    const taskId = e.dataTransfer.getData('text/plain');
    const task = tasks.find(t => t.taskId === taskId);
    if (!task) return;

    if (canEditTask(task)) {
      updateStatusMutation.mutate({ taskId, status: targetStatus });
    } else {
      alert("Permission denied. You can only update tasks assigned to you, created by you, or belonging to your department.");
    }
  };

  const today = new Date();
  today.setHours(0,0,0,0);

  const calculateMetrics = () => {
    const activeTasks = tasks.filter(t => t.status !== 'CANCELLED');
    const total = activeTasks.length;
    if (total === 0) return { total: 0, completed: 0, completionRate: 0, delayed: 0, blocked: 0, overdue: 0, verify: 0 };

    const completed = activeTasks.filter(t => t.status === 'COMPLETED').length;
    const verify = activeTasks.filter(t => t.status === 'VERIFY').length;
    const delayed = activeTasks.filter(t => t.status === 'DELAYED').length;
    const blocked = activeTasks.filter(t => t.status === 'BLOCKED').length;

    let overdue = 0;
    activeTasks.forEach(t => {
      if (t.status !== 'COMPLETED' && t.deadline) {
        const deadDate = new Date(t.deadline);
        if (!isNaN(deadDate.getTime()) && deadDate < today) {
          overdue++;
        }
      }
    });

    const completionRate = Math.round((completed / total) * 100);
    return { total, completed, completionRate, delayed, blocked, overdue, verify };
  };

  const metrics = calculateMetrics();

  // Filtering
  const filteredTasks = tasks.filter(task => {
    if (task.status === 'CANCELLED') return false;

    const subs = parseDepartmentAssignments(task.departmentAssignments);
    const inSubTeams = subs.some(s => s.teamId === filterTeam);
    const inSubAssignees = subs.some(s => s.assignedTo === filterAssignee);

    if (filterTeam && task.teamId !== filterTeam && !inSubTeams) return false;
    if (filterAssignee && task.assignedTo !== filterAssignee && !inSubAssignees) return false;
    if (filterEvent && task.eventId !== filterEvent) return false;
    if (filterPriority && task.priority !== filterPriority) return false;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      const titleMatch = task.taskTitle?.toLowerCase().includes(q);
      const descMatch = task.taskDescription?.toLowerCase().includes(q);
      const idMatch = task.taskId?.toLowerCase().includes(q);
      if (!titleMatch && !descMatch && !idMatch) return false;
    }
    return true;
  });

  const getPriorityColor = (priority: string) => {
    const p = priority?.toUpperCase() || 'MEDIUM';
    if (p === 'CRITICAL') return 'bg-red-500/10 text-red-700 border-red-200/50';
    if (p === 'HIGH') return 'bg-orange-500/10 text-orange-700 border-orange-200/50';
    if (p === 'MEDIUM') return 'bg-blue-50/80 text-blue-700 border-blue-200/50';
    return 'bg-slate-100 text-slate-600 border-slate-200';
  };

  const isOverdue = (task: Task) => {
    if (task.status === 'COMPLETED') return false;
    if (!task.deadline) return false;
    const deadDate = new Date(task.deadline);
    return !isNaN(deadDate.getTime()) && deadDate < today;
  };

  if (tasksLoading) {
    return <Loading message="Loading Kanban lanes & task assignments..." />;
  }

  if (tasksError) {
    return (
      <ErrorState 
        title="Failed to load tasks" 
        message={tasksError instanceof Error ? tasksError.message : 'Error communicating with sheet repository.'} 
        onRetry={refetchTasks}
      />
    );
  }

  return (
    <div className="space-y-lg animate-fade-in text-left">
      {/* 1. Header with Quick Metrics */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-md">
        <div className="space-y-xxs">
          <div className="flex items-center gap-xs">
            <span className="text-primary font-semibold text-caption-strong uppercase">Workflow </span>
            <span className="bg-primary/10 text-primary text-[11px] font-semibold px-xs py-[2px] rounded-pill"></span>
          </div>
          <h1 className="text-display-md font-bold text-ink tracking-tight">Task Board</h1>
          <p className="text-caption-spec text-ink-muted48">
            Manage multi-department deliverables, track operator sub-progress, and verify outcomes in real-time.
          </p>
        </div>

        {(role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN' || role === 'LEAD') && (
          <button
            onClick={() => setIsCreateModalOpen(true)}
            className="apple-btn-primary flex items-center gap-xs py-[10px] px-lg shrink-0 shadow-sm"
          >
            <Plus className="w-4 h-4" /> New Task
          </button>
        )}
      </div>

      {/* 2. Metrics Indicator Strip */}
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-sm">
        <div className="bg-canvas border border-hairline rounded-lg p-sm shadow-product-surface space-y-xxs">
          <span className="text-micro-legal text-ink-muted48 font-semibold uppercase tracking-wider">Total Active</span>
          <div className="text-[18px] font-bold text-ink">{metrics.total}</div>
        </div>
        <div className="bg-canvas border border-hairline rounded-lg p-sm shadow-product-surface space-y-xxs">
          <span className="text-micro-legal text-ink-muted48 font-semibold uppercase tracking-wider">Completed</span>
          <div className="text-[18px] font-bold text-green-600 flex items-center justify-between">
            <span>{metrics.completed}</span>
            <span className="text-[11px] font-mono text-ink-muted48 font-normal">{metrics.completionRate}%</span>
          </div>
        </div>
        <div className="bg-canvas border border-hairline rounded-lg p-sm shadow-product-surface space-y-xxs">
          <span className="text-micro-legal text-ink-muted48 font-semibold uppercase tracking-wider">Verification</span>
          <div className="text-[18px] font-bold text-purple-600">{metrics.verify}</div>
        </div>
        <div className="bg-canvas border border-hairline rounded-lg p-sm shadow-product-surface space-y-xxs">
          <span className="text-micro-legal text-ink-muted48 font-semibold uppercase tracking-wider">Overdue</span>
          <div className="text-[18px] font-bold text-red-600">{metrics.overdue}</div>
        </div>
        <div className="bg-canvas border border-hairline rounded-lg p-sm shadow-product-surface space-y-xxs">
          <span className="text-micro-legal text-ink-muted48 font-semibold uppercase tracking-wider">Delayed</span>
          <div className="text-[18px] font-bold text-amber-600">{metrics.delayed}</div>
        </div>
        <div className="bg-canvas border border-hairline rounded-lg p-sm shadow-product-surface space-y-xxs">
          <span className="text-micro-legal text-ink-muted48 font-semibold uppercase tracking-wider">Blocked</span>
          <div className="text-[18px] font-bold text-red-700">{metrics.blocked}</div>
        </div>
      </div>

      {/* 3. Search & Filter Bar */}
      <div className="flex flex-col lg:flex-row gap-sm items-stretch lg:items-center justify-between bg-canvas border border-hairline rounded-lg p-sm shadow-product-surface">
        <div className="relative flex-1">
          <Search className="w-4 h-4 absolute left-sm top-1/2 -translate-y-1/2 text-ink-muted48" />
          <input 
            type="text"
            placeholder="Search by task title, description, or TSK-ID..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-transparent pl-[32px] pr-sm py-[6px] text-[13px] text-ink focus:outline-none placeholder:text-ink-muted48"
          />
        </div>

        <div className="flex flex-wrap items-center gap-xs border-t lg:border-t-0 border-hairline pt-xs lg:pt-0">
          <select
            value={filterTeam}
            onChange={(e) => setFilterTeam(e.target.value)}
            className="bg-canvas border border-hairline rounded-md px-sm py-[6px] text-[12px] text-ink focus:outline-none"
          >
            <option value="">All Departments</option>
            {teams.map(t => (
              <option key={t.teamId} value={t.teamId}>{t.teamName}</option>
            ))}
          </select>

          <select
            value={filterAssignee}
            onChange={(e) => setFilterAssignee(e.target.value)}
            className="bg-canvas border border-hairline rounded-md px-sm py-[6px] text-[12px] text-ink focus:outline-none"
          >
            <option value="">All Assignees</option>
            {users.map(u => (
              <option key={u.userId} value={u.userId}>{u.name}</option>
            ))}
          </select>

          <select
            value={filterEvent}
            onChange={(e) => setFilterEvent(e.target.value)}
            className="bg-canvas border border-hairline rounded-md px-sm py-[6px] text-[12px] text-ink focus:outline-none"
          >
            <option value="">All Events</option>
            {events.map(ev => (
              <option key={ev.eventId} value={ev.eventId}>{ev.eventName}</option>
            ))}
          </select>

          <select
            value={filterPriority}
            onChange={(e) => setFilterPriority(e.target.value)}
            className="bg-canvas border border-hairline rounded-md px-sm py-[6px] text-[12px] text-ink focus:outline-none"
          >
            <option value="">All Priorities</option>
            <option value="LOW">Low</option>
            <option value="MEDIUM">Medium</option>
            <option value="HIGH">High</option>
            <option value="CRITICAL">Critical</option>
          </select>

          {(filterTeam || filterAssignee || filterEvent || filterPriority || searchQuery) && (
            <button 
              onClick={() => {
                setFilterTeam('');
                setFilterAssignee('');
                setFilterEvent('');
                setFilterPriority('');
                setSearchQuery('');
              }}
              className="text-[12px] text-primary font-semibold hover:underline whitespace-nowrap px-xs"
            >
              Reset
            </button>
          )}
        </div>
      </div>

      {/* 4. Kanban Lanes Board */}
      <div className="overflow-x-auto -mx-lg px-lg sm:-mx-xl sm:px-xl md:mx-0 md:px-0 pb-lg">
        <div className="flex md:grid md:grid-cols-3 lg:grid-cols-6 gap-md min-w-[1100px] md:min-w-0 select-none snap-x snap-mandatory md:snap-none">
          {LANES.map(lane => {
            const laneTasks = filteredTasks.filter(t => {
              if (lane.id === 'IN_PROGRESS') {
                return t.status === 'IN_PROGRESS' || t.status === 'REJECTED';
              }
              return t.status === lane.id;
            });
            
            return (
              <div 
                key={lane.id}
                onDragOver={handleDragOver}
                onDrop={(e) => handleDrop(e, lane.id)}
                className="flex flex-col w-[240px] md:w-auto flex-shrink-0 md:flex-shrink bg-canvas-parchment/30 border border-hairline rounded-lg shadow-inner-soft p-sm min-h-[420px] snap-start"
              >
                {/* Lane Header */}
                <div className={`px-sm py-xxs border rounded-pill flex items-center justify-between font-text text-[12px] font-semibold mb-sm ${lane.color}`}>
                  <span>{lane.title}</span>
                  <span className="w-5 h-5 rounded-full bg-canvas border border-hairline flex items-center justify-center text-[10px] text-ink font-bold">
                    {laneTasks.length}
                  </span>
                </div>

                {/* Lane Cards Container */}
                <div className="flex-1 space-y-sm overflow-y-auto max-h-[600px] scrollbar-thin">
                  {laneTasks.length === 0 ? (
                    <div className="h-full border border-dashed border-hairline rounded-md flex items-center justify-center py-xl text-caption-spec text-ink-muted32">
                      Drop items here
                    </div>
                  ) : (
                    laneTasks.map(task => {
                      const assigneeName = users.find(u => u.userId === task.assignedTo)?.name || 'Unassigned';
                      const subAssignments = parseDepartmentAssignments(task.departmentAssignments);
                      const isRejected = task.status === 'REJECTED';
                      const isUnderVerification = task.status === 'VERIFY';

                      return (
                        <div
                          key={task.taskId}
                          draggable
                          onDragStart={(e) => handleDragStart(e, task)}
                          onClick={() => setSelectedTask(task)}
                          className={`bg-canvas border rounded-md p-md shadow-product-surface space-y-xs cursor-pointer hover:border-primary hover:shadow-md transition-all active:scale-[0.98] text-left ${
                            isRejected 
                              ? 'border-red-300 bg-red-50/20' 
                              : isUnderVerification 
                              ? 'border-purple-300 bg-purple-50/20' 
                              : 'border-hairline'
                          }`}
                        >
                          <div className="flex items-start justify-between gap-xs">
                            <span className="text-[10px] font-mono text-ink-muted32 font-bold">{task.taskId}</span>
                            <div className="flex items-center gap-[4px]">
                              {isOverdue(task) && (
                                <span className="px-xxs py-[1px] text-[8.5px] font-bold bg-red-100 text-red-700 rounded-sm">
                                  Overdue
                                </span>
                              )}
                              {isRejected && (
                                <span className="px-xxs py-[1px] text-[8.5px] font-bold bg-red-100 text-red-700 rounded-sm">
                                  Changes Needed
                                </span>
                              )}
                              {isUnderVerification && (
                                <span className="px-xxs py-[1px] text-[8.5px] font-bold bg-purple-100 text-purple-700 rounded-sm">
                                  Under Review
                                </span>
                              )}
                              {subAssignments.length > 0 && (
                                <span className="px-xxs py-[1px] text-[8.5px] font-bold bg-blue-100 text-blue-700 rounded-sm flex items-center gap-[2px]">
                                  <Layers className="w-2.5 h-2.5" /> Multi-Team
                                </span>
                              )}
                              <span className={`px-xxs py-[1px] text-[9px] font-semibold border rounded-sm uppercase tracking-wider font-mono ${getPriorityColor(task.priority)}`}>
                                {task.priority}
                              </span>
                            </div>
                          </div>

                          <div className="space-y-xxs">
                            <h4 className="text-[13px] font-bold text-ink leading-tight line-clamp-2">{task.taskTitle}</h4>
                            {task.taskDescription && (
                              <p className="text-[11px] text-ink-muted48 line-clamp-2 leading-relaxed">{task.taskDescription}</p>
                            )}
                          </div>

                          {/* Rejection Note */}
                          {isRejected && task.rejectionRemarks && (
                            <div className="p-xs bg-red-50 border border-red-200 rounded text-[10px] text-red-700 leading-snug">
                              <strong>Feedback:</strong> {task.rejectionRemarks}
                            </div>
                          )}

                          {/* Multi-Department Sub-Progress Section */}
                          {subAssignments.length > 0 ? (
                            <div className="space-y-[3px] pt-xxs border-t border-hairline">
                              <span className="text-[9.5px] font-bold uppercase tracking-wider text-ink-muted48 flex items-center justify-between">
                                <span>Department Progress:</span>
                                <span className="font-mono text-primary font-bold">{task.completionPercent || 0}% Total</span>
                              </span>
                              <div className="space-y-[3px]">
                                {subAssignments.map((sub, sIdx) => (
                                  <div key={sIdx} className="bg-canvas-parchment/60 border border-hairline rounded px-xs py-[2px] text-[10px] flex items-center justify-between">
                                    <span className="font-semibold text-ink truncate max-w-[85px]">
                                      {sub.teamName || sub.teamId}:
                                    </span>
                                    <div className="flex items-center gap-xs">
                                      <span className="text-ink-muted80 font-mono font-bold">{sub.progress || 0}%</span>
                                      <span className={`text-[8.5px] font-bold px-[3px] py-[1px] rounded ${
                                        sub.progress === 100 || sub.status === 'COMPLETED' ? 'bg-green-100 text-green-700' :
                                        sub.status === 'VERIFY' ? 'bg-purple-100 text-purple-700' :
                                        sub.progress > 0 ? 'bg-blue-100 text-blue-700' :
                                        'bg-slate-100 text-slate-600'
                                      }`}>
                                        {sub.status || (sub.progress === 0 ? 'NOT_STARTED' : 'IN_PROGRESS')}
                                      </span>
                                    </div>
                                  </div>
                                ))}
                              </div>
                            </div>
                          ) : (
                            /* Standard Single-Task Progress Bar */
                            <div className="space-y-xxs pt-xxs">
                              <div className="flex items-center justify-between text-[10px] text-ink-muted48 font-mono">
                                <span>Progress</span>
                                <span>{task.completionPercent || 0}%</span>
                              </div>
                              <div className="w-full bg-ink-muted8 h-[4px] rounded-full overflow-hidden">
                                <div 
                                  className={`h-full rounded-full transition-all duration-300 ${
                                    task.status === 'COMPLETED' ? 'bg-green-500' : isUnderVerification ? 'bg-purple-500' : 'bg-primary'
                                  }`} 
                                  style={{ width: `${task.completionPercent || 0}%` }}
                                ></div>
                              </div>
                            </div>
                          )}

                          <div className="border-t border-hairline pt-xxs flex items-center justify-between text-[10px] text-ink-muted48">
                            <span className="truncate max-w-[110px] flex items-center gap-xxs" title={assigneeName}>
                              👤 {subAssignments.length > 0 ? `${subAssignments.length} Teams Assigned` : assigneeName}
                            </span>
                            {task.assignedTo && (
                              <button 
                                onClick={(e) => handleWhatsAppReminder(e, task)}
                                className="p-[2px] hover:bg-green-50 hover:text-green-600 rounded transition"
                                title="Send WhatsApp Reminder"
                              >
                                <MessageCircle className="w-3.5 h-3.5 text-green-600" />
                              </button>
                            )}
                          </div>
                        </div>
                      );
                    })
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* CREATE TASK MODAL */}
      {isCreateModalOpen && (
        <CreateTaskModal
          teams={teams}
          users={users}
          events={events}
          onSubmit={(data) => createTaskMutation.mutate(data)}
          isSubmitting={createTaskMutation.isPending}
          onClose={() => setIsCreateModalOpen(false)}
        />
      )}

      {/* EDIT / VIEW TASK MODAL */}
      {selectedTask && (
        <EditTaskModal
          task={selectedTask}
          users={users}
          myUserId={myUserId}
          canEditTask={canEditTask(selectedTask)}
          canEditAdminFields={canEditAdminFields(selectedTask)}
          canVerifyTask={canVerifyTask(selectedTask)}
          canDeleteTask={canDeleteTask(selectedTask)}
          onDeleteTask={(taskId) => deleteTaskMutation.mutate(taskId)}
          onSubmit={(taskId, payload) => editTaskMutation.mutate({ taskId, payload })}
          onSubmitForVerification={(taskId, remarks, verifierId) => submitVerificationMutation.mutate({ taskId, remarks, verifierId })}
          onVerify={(taskId, remarks) => verifyMutation.mutate({ taskId, remarks })}
          onReject={(taskId, remarks) => rejectMutation.mutate({ taskId, remarks })}
          isSubmitting={editTaskMutation.isPending || submitVerificationMutation.isPending || verifyMutation.isPending || rejectMutation.isPending}
          onClose={() => setSelectedTask(null)}
        />
      )}
    </div>
  );
};

/* -------------------------------------------------------------
 * CREATE TASK MODAL COMPONENT (WITH MULTI-DEPARTMENT SUPPORT)
 * ------------------------------------------------------------- */
interface CreateModalProps {
  teams: Team[];
  users: User[];
  events: EventItem[];
  onSubmit: (data: any) => void;
  isSubmitting: boolean;
  onClose: () => void;
}

const CreateTaskModal: React.FC<CreateModalProps> = ({ teams, users, events, onSubmit, isSubmitting, onClose }) => {
  const [title, setTitle] = useState('');
  const [desc, setDesc] = useState('');
  const [priority, setPriority] = useState('MEDIUM');
  const [deadline, setDeadline] = useState('');
  const [eventVal, setEventVal] = useState('');
  const [drive, setDrive] = useState('');
  const [verifier, setVerifier] = useState('');

  // Multi-department assignment state
  const [isMultiDept, setIsMultiDept] = useState(false);
  const [singleTeam, setSingleTeam] = useState('');
  const [singleAssignee, setSingleAssignee] = useState('');

  // Multi-department rows: [{ teamId, assignedTo }]
  const [deptRows, setDeptRows] = useState<{ teamId: string; assignedTo: string }[]>([
    { teamId: teams[0]?.teamId || '', assignedTo: '' }
  ]);

  const handleAddDeptRow = () => {
    setDeptRows([...deptRows, { teamId: '', assignedTo: '' }]);
  };

  const handleRemoveDeptRow = (index: number) => {
    setDeptRows(deptRows.filter((_, idx) => idx !== index));
  };

  const handleUpdateDeptRow = (index: number, field: 'teamId' | 'assignedTo', val: string) => {
    const updated = [...deptRows];
    updated[index][field] = val;
    if (field === 'teamId') {
      updated[index].assignedTo = '';
    }
    setDeptRows(updated);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) {
      alert("Title is required!");
      return;
    }

    let departmentAssignments: DepartmentAssignment[] = [];
    if (isMultiDept) {
      const validRows = deptRows.filter(r => r.teamId);
      if (validRows.length === 0) {
        alert("Please select at least one department for multi-team task.");
        return;
      }
      departmentAssignments = validRows.map(r => {
        const teamObj = teams.find(t => t.teamId === r.teamId);
        const userObj = users.find(u => u.userId === r.assignedTo);
        return {
          teamId: r.teamId,
          teamName: teamObj?.teamName || r.teamId,
          assignedTo: r.assignedTo,
          assigneeName: userObj?.name || 'Unassigned',
          status: 'NOT_STARTED',
          progress: 0,
          remarks: ''
        };
      });
    }

    const payload: any = {
      taskTitle: title,
      taskDescription: desc,
      priority,
      deadline: deadline || undefined,
      eventId: eventVal,
      driveLink: drive,
      verifierId: verifier || undefined
    };

    if (isMultiDept && departmentAssignments.length > 0) {
      payload.departmentAssignments = JSON.stringify(departmentAssignments);
      payload.teamId = departmentAssignments[0].teamId;
      payload.assignedTo = departmentAssignments[0].assignedTo;
    } else {
      payload.teamId = singleTeam;
      payload.assignedTo = singleAssignee;
    }

    onSubmit(payload);
  };

  return (
    <div className="fixed inset-0 bg-canvas/60 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center sm:p-md select-none font-text text-ink safe-top safe-bottom safe-left safe-right">
      <div className="bg-canvas border border-hairline sm:rounded-xl rounded-t-xl shadow-product-surface max-w-[560px] w-full p-lg space-y-md animate-scale-up text-left max-h-[calc(90dvh-env(safe-area-inset-top,0px))] overflow-y-auto safe-bottom">
        <div className="flex items-center justify-between border-b border-hairline pb-xs">
          <div>
            <h3 className="text-body-strong font-bold text-ink text-[16px]">Initialize Operations Task</h3>
            <p className="text-[11px] text-ink-muted48">Create single-owner or multi-department cross-functional tasks.</p>
          </div>
          <button onClick={onClose} className="p-xxs hover:bg-ink-muted8 rounded-md transition">
            <X className="w-4 h-4 text-ink-muted48 hover:text-ink" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-sm text-[13px]">
          <div className="space-y-xxs">
            <label className="font-semibold text-caption-strong">Task Title *</label>
            <input
              type="text"
              required
              placeholder="e.g. Publish Monthly Newsletter (Content, Design & Tech Sync)"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
            />
          </div>

          <div className="space-y-xxs">
            <label className="font-semibold text-caption-strong">Description / Scope Details</label>
            <textarea
              placeholder="Provide scope details, guidelines, and deliverables..."
              value={desc}
              onChange={(e) => setDesc(e.target.value)}
              className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink focus:border-primary focus:outline-none min-h-[50px]"
            />
          </div>

          {/* Mode Switch: Single Department vs Multi-Department */}
          <div className="bg-canvas-parchment/60 border border-hairline rounded-lg p-sm space-y-sm">
            <div className="flex items-center justify-between">
              <label className="font-bold text-[12px] text-ink flex items-center gap-xs">
                <Users2 className="w-4 h-4 text-primary" />
                <span>Multi-Department Assignment</span>
              </label>
              <button
                type="button"
                onClick={() => setIsMultiDept(!isMultiDept)}
                className={`px-sm py-[4px] rounded-pill text-[11px] font-bold transition ${
                  isMultiDept ? 'bg-primary text-white shadow-xs' : 'bg-ink-muted8 text-ink-muted80'
                }`}
              >
                {isMultiDept ? 'Multi-Team ON' : 'Single Team'}
              </button>
            </div>

            {isMultiDept ? (
              <div className="space-y-xs pt-xxs">
                <p className="text-[11px] text-ink-muted48">
                  Assign this task across multiple departments (e.g. Design, Content, Tech). Each assignee can independently track their sub-progress.
                </p>
                {deptRows.map((row, idx) => (
                  <div key={idx} className="flex items-center gap-xs bg-canvas border border-hairline rounded-md p-xs">
                    <select
                      value={row.teamId}
                      onChange={(e) => handleUpdateDeptRow(idx, 'teamId', e.target.value)}
                      className="flex-1 bg-transparent border border-hairline rounded px-xs py-[6px] text-[12px] text-ink focus:outline-none"
                    >
                      <option value="">Select Department</option>
                      {teams.map(t => (
                        <option key={t.teamId} value={t.teamId}>{t.teamName}</option>
                      ))}
                    </select>

                    <select
                      value={row.assignedTo}
                      onChange={(e) => handleUpdateDeptRow(idx, 'assignedTo', e.target.value)}
                      className="flex-1 bg-transparent border border-hairline rounded px-xs py-[6px] text-[12px] text-ink focus:outline-none font-semibold text-primary"
                    >
                      <option value="">Select Assignee</option>
                      {users
                        .filter(u => !row.teamId || u.teamId === row.teamId)
                        .map(u => (
                          <option key={u.userId} value={u.userId}>{u.name}</option>
                        ))
                      }
                    </select>

                    {deptRows.length > 1 && (
                      <button
                        type="button"
                        onClick={() => handleRemoveDeptRow(idx)}
                        className="p-xxs text-red-500 hover:bg-red-50 rounded transition"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    )}
                  </div>
                ))}

                <button
                  type="button"
                  onClick={handleAddDeptRow}
                  className="apple-btn-secondary py-[4px] px-sm text-[11px] flex items-center gap-xxs font-semibold"
                >
                  <Plus className="w-3.5 h-3.5" /> Add Another Department
                </button>
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm pt-xxs">
                <div className="space-y-xxs">
                  <label className="font-semibold text-caption-strong">Department</label>
                  <select
                    value={singleTeam}
                    onChange={(e) => {
                      setSingleTeam(e.target.value);
                      setSingleAssignee('');
                    }}
                    className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
                  >
                    <option value="">Unassigned Team</option>
                    {teams.map(t => (
                      <option key={t.teamId} value={t.teamId}>{t.teamName}</option>
                    ))}
                  </select>
                </div>

                <div className="space-y-xxs">
                  <label className="font-semibold text-caption-strong">Assignee Operator</label>
                  <select
                    value={singleAssignee}
                    onChange={(e) => setSingleAssignee(e.target.value)}
                    className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
                  >
                    <option value="">Unassigned User</option>
                    {users
                      .filter(u => !singleTeam || u.teamId === singleTeam)
                      .map(u => (
                        <option key={u.userId} value={u.userId}>{u.name}</option>
                      ))
                    }
                  </select>
                </div>
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Assign Verifier (Approver)</label>
              <select
                value={verifier}
                onChange={(e) => setVerifier(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="">Default (Task Assigner / Lead)</option>
                {users.map(u => (
                  <option key={u.userId} value={u.userId}>
                    {u.name} ({u.role})
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Priority</label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="LOW">Low</option>
                <option value="MEDIUM">Medium</option>
                <option value="HIGH">High</option>
                <option value="CRITICAL">Critical</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Task Deadline</label>
              <input
                type="date"
                value={deadline}
                onChange={(e) => setDeadline(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink focus:border-primary focus:outline-none font-mono"
              />
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Target Event</label>
              <select
                value={eventVal}
                onChange={(e) => setEventVal(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="">None / General Operations</option>
                {events.map(ev => (
                  <option key={ev.eventId} value={ev.eventId}>{ev.eventName}</option>
                ))}
              </select>
            </div>
          </div>

          <div className="space-y-xxs">
            <label className="font-semibold text-caption-strong">Google Drive Asset URL</label>
            <input
              type="url"
              placeholder="https://drive.google.com/..."
              value={drive}
              onChange={(e) => setDrive(e.target.value)}
              className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
            />
          </div>

          <div className="flex justify-end gap-sm pt-xs border-t border-hairline">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="apple-btn-secondary py-[8px] px-md select-none active:scale-[0.98] transition"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="apple-btn-primary py-[8px] px-lg select-none active:scale-[0.98] transition"
            >
              {isSubmitting ? 'Creating...' : 'Initialize Task'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

/* -------------------------------------------------------------
 * EDIT / VIEW TASK MODAL COMPONENT (WITH SUB-PROGRESS SLIDERS)
 * ------------------------------------------------------------- */
interface EditModalProps {
  task: Task;
  users: User[];
  myUserId: string;
  canEditTask: boolean;
  canEditAdminFields: boolean;
  canVerifyTask: boolean;
  canDeleteTask: boolean;
  onDeleteTask: (taskId: string) => void;
  onSubmit: (taskId: string, data: Partial<Task> & { remarks?: string }) => void;
  onSubmitForVerification: (taskId: string, remarks?: string, verifierId?: string) => void;
  onVerify: (taskId: string, remarks?: string) => void;
  onReject: (taskId: string, remarks: string) => void;
  isSubmitting: boolean;
  onClose: () => void;
}

const EditTaskModal: React.FC<EditModalProps> = ({ 
  task, 
  users, 
  myUserId,
  canEditTask,
  canEditAdminFields, 
  canVerifyTask,
  canDeleteTask,
  onDeleteTask,
  onSubmit, 
  onSubmitForVerification,
  onVerify,
  onReject,
  isSubmitting,
  onClose 
}) => {
  const { profile } = useAuth();
  const role = profile?.role || 'MEMBER';
  const myTeamId = profile?.teamId || '';

  const [status, setStatus] = useState(task.status);
  const [progress, setProgress] = useState<number>(task.completionPercent || 0);
  const [remarks, setRemarks] = useState('');

  // Multi-department sub-assignments state
  const [subAssignments, setSubAssignments] = useState<DepartmentAssignment[]>(() => {
    return parseDepartmentAssignments(task.departmentAssignments);
  });

  const [isSubmitDialogOpen, setIsSubmitDialogOpen] = useState(false);
  const [submitVerifier, setSubmitVerifier] = useState(task.verifierId || task.assignedBy || '');
  const [submitNote, setSubmitNote] = useState('');

  const [isRejectDialogOpen, setIsRejectDialogOpen] = useState(false);
  const [rejectionInput, setRejectionInput] = useState('');

  // Administrative restricted fields
  const [title, setTitle] = useState(task.taskTitle);
  const [desc, setDesc] = useState(task.taskDescription || '');
  const [verifier, setVerifier] = useState(task.verifierId || '');
  const [priority, setPriority] = useState(task.priority);
  const [deadline, setDeadline] = useState(task.deadline ? new Date(task.deadline).toISOString().split('T')[0] : '');
  const [drive, setDrive] = useState(task.driveLink || '');

  const isOwner = task.assignedTo === myUserId || subAssignments.some(s => s.assignedTo === myUserId);
  const isUnderVerification = task.status === 'VERIFY';
  const isRejected = task.status === 'REJECTED';

  const currentVerifierName = users.find(u => u.userId === (task.verifierId || task.assignedBy))?.name || 'Assigned Verifier';

  // Handle individual department sub-progress adjustment
  const handleSubProgressChange = (index: number, newProgress: number) => {
    const updated = [...subAssignments];
    updated[index].progress = newProgress;
    if (newProgress === 100) {
      updated[index].status = 'COMPLETED';
    } else if (newProgress > 0 && updated[index].status === 'NOT_STARTED') {
      updated[index].status = 'IN_PROGRESS';
    }
    setSubAssignments(updated);

    // Compute new aggregate total
    const total = updated.reduce((acc, curr) => acc + curr.progress, 0);
    const avg = Math.round(total / updated.length);
    setProgress(avg);
  };

  const handleSubStatusChange = (index: number, newStatus: string) => {
    const updated = [...subAssignments];
    updated[index].status = newStatus;
    if (newStatus === 'COMPLETED') {
      updated[index].progress = 100;
    } else if (newStatus === 'NOT_STARTED') {
      updated[index].progress = 0;
    }
    setSubAssignments(updated);

    const total = updated.reduce((acc, curr) => acc + curr.progress, 0);
    const avg = Math.round(total / updated.length);
    setProgress(avg);
  };

  const handleSubRemarksChange = (index: number, val: string) => {
    const updated = [...subAssignments];
    updated[index].remarks = val;
    setSubAssignments(updated);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const payload: any = {
      status,
      completionPercent: Number(progress),
      verifierId: verifier || undefined,
      remarks: remarks || 'Task modified.'
    };

    if (subAssignments.length > 0) {
      payload.departmentAssignments = JSON.stringify(subAssignments);
    }

    if (canEditAdminFields) {
      payload.taskTitle = title;
      payload.taskDescription = desc;
      payload.priority = priority;
      payload.deadline = deadline || null;
      payload.driveLink = drive;
    }

    onSubmit(task.taskId, payload);
  };

  const handleStatusChange = (newStatus: string) => {
    setStatus(newStatus);
    if (newStatus === 'COMPLETED' || newStatus === 'VERIFY') {
      setProgress(100);
    } else if (newStatus === 'NOT_STARTED') {
      setProgress(0);
    }
  };

  const handleProgressChange = (newProgress: number) => {
    setProgress(newProgress);
    if (newProgress === 100) {
      if (status !== 'VERIFY') setStatus('COMPLETED');
    } else if (task.status === 'COMPLETED' && newProgress < 100) {
      setStatus(newProgress === 0 ? 'NOT_STARTED' : 'IN_PROGRESS');
    }
  };

  const handleConfirmSubmitVerification = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmitForVerification(task.taskId, submitNote || "Deliverables submitted for review.", submitVerifier);
    setIsSubmitDialogOpen(false);
  };

  const handleConfirmReject = (e: React.FormEvent) => {
    e.preventDefault();
    if (!rejectionInput.trim()) {
      alert("Please provide feedback or the reason changes are required.");
      return;
    }
    onReject(task.taskId, rejectionInput.trim());
    setIsRejectDialogOpen(false);
  };

  return (
    <div className="fixed inset-0 bg-canvas/60 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center sm:p-md select-none font-text text-ink safe-top safe-bottom safe-left safe-right">
      <div className="bg-canvas border border-hairline sm:rounded-xl rounded-t-xl shadow-product-surface max-w-[580px] w-full p-lg space-y-md animate-scale-up text-left max-h-[calc(92dvh-env(safe-area-inset-top,0px))] overflow-y-auto safe-bottom">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-hairline pb-xs">
          <div className="space-y-[2px]">
            <span className="text-[10px] font-mono text-ink-muted48 uppercase">Task ID: {task.taskId}</span>
            <h3 className="text-body-strong font-bold text-ink flex items-center gap-xs">
              {task.taskTitle}
            </h3>
          </div>
          <button onClick={onClose} className="p-xxs hover:bg-ink-muted8 rounded-md transition">
            <X className="w-4 h-4 text-ink-muted48 hover:text-ink" />
          </button>
        </div>

        {!canEditTask && (
          <div className="p-sm bg-amber-50 border border-amber-200 rounded-lg text-[12px] text-amber-900 flex items-center gap-xs animate-fade-in">
            <span>🔒 <strong>Read-Only View:</strong> You do not have permission to modify this task.</span>
          </div>
        )}

        {isRejected && task.rejectionRemarks && (
          <div className="p-md bg-red-50 border border-red-200 rounded-lg space-y-xxs animate-fade-in text-red-800">
            <div className="flex items-center gap-xs font-bold text-[13px] text-red-700">
              <AlertCircle className="w-4 h-4 text-red-600" />
              <span>Changes Requested by Verifier</span>
            </div>
            <p className="text-[12px] text-red-900 leading-relaxed pl-[20px]">
              "{task.rejectionRemarks}"
            </p>
          </div>
        )}

        {/* Verification Review Banner */}
        {isUnderVerification && (
          <div className="p-md bg-purple-50 border border-purple-200 rounded-lg space-y-sm animate-fade-in">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-xs font-bold text-[13px] text-purple-900">
                <ShieldCheck className="w-4 h-4 text-purple-700" />
                <span>Verification Review in Progress</span>
              </div>
              <span className="text-[11px] font-semibold text-purple-700 bg-purple-100 px-xs py-[2px] rounded-pill">
                Verifier: {currentVerifierName}
              </span>
            </div>
            {canVerifyTask && (
              <div className="flex flex-wrap items-center gap-sm pt-xxs">
                <button
                  type="button"
                  disabled={isSubmitting}
                  onClick={() => onVerify(task.taskId, "Verified and approved on task board.")}
                  className="flex-1 apple-btn-primary bg-green-600 hover:bg-green-700 text-[12px] py-[8px] flex items-center justify-center gap-xs shadow-sm"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  Approve & Complete
                </button>
                <button
                  type="button"
                  disabled={isSubmitting}
                  onClick={() => setIsRejectDialogOpen(true)}
                  className="flex-1 bg-white border border-red-300 text-red-700 hover:bg-red-50 text-[12px] font-semibold py-[8px] px-md rounded-pill flex items-center justify-center gap-xs transition shadow-sm"
                >
                  <RotateCcw className="w-4 h-4" />
                  Request Changes
                </button>
              </div>
            )}
          </div>
        )}

        {/* Submit for Verification Button */}
        {canEditTask && (!isUnderVerification && task.status !== 'COMPLETED') && (isOwner || canEditAdminFields) && (
          <div className="p-sm bg-blue-50/60 border border-blue-200 rounded-lg flex items-center justify-between gap-sm">
            <div className="space-y-[2px]">
              <span className="text-[12px] font-bold text-blue-900">Finished your deliverables?</span>
              <p className="text-[11px] text-blue-700">Submit this task to an approver for official verification.</p>
            </div>
            <button
              type="button"
              disabled={isSubmitting}
              onClick={() => setIsSubmitDialogOpen(true)}
              className="apple-btn-primary bg-primary hover:bg-primary-focus text-[12px] py-[7px] px-md flex items-center gap-xs shrink-0 shadow-sm"
            >
              <Send className="w-3.5 h-3.5" />
              Submit for Verification
            </button>
          </div>
        )}

        {/* Verification Modal Dialog */}
        {isSubmitDialogOpen && (
          <form onSubmit={handleConfirmSubmitVerification} className="p-md bg-white border-2 border-primary/40 rounded-lg shadow-md space-y-sm animate-scale-up text-left">
            <div className="space-y-xxs">
              <h4 className="font-bold text-[13px] text-primary">Submit for Verification</h4>
              <p className="text-[11px] text-ink-muted48">Select who should verify this task and add any delivery remarks.</p>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong text-ink">Assign Verifier (Approver) *</label>
              <select
                required
                value={submitVerifier}
                onChange={(e) => setSubmitVerifier(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-[13px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="">Select an approver...</option>
                {users.map(u => (
                  <option key={u.userId} value={u.userId}>
                    {u.name} ({u.role}{u.position ? ` - ${u.position}` : ''})
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong text-ink">Delivery Remarks / Progress Link</label>
              <textarea
                rows={2}
                placeholder="e.g. Completed design assets. Drive folder updated with high-res PNG and source PSD files."
                value={submitNote}
                onChange={(e) => setSubmitNote(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md p-sm text-[12px] text-ink focus:border-primary focus:outline-none"
              />
            </div>

            <div className="flex justify-end gap-sm pt-xs border-t border-hairline">
              <button
                type="button"
                onClick={() => setIsSubmitDialogOpen(false)}
                className="px-md py-[6px] text-[12px] border border-hairline rounded-md hover:bg-ink-muted8"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-lg py-[6px] text-[12px] apple-btn-primary flex items-center gap-xs shadow-sm"
              >
                <Send className="w-3.5 h-3.5" />
                Confirm & Submit
              </button>
            </div>
          </form>
        )}

        {/* Reject Dialog Popover */}
        {isRejectDialogOpen && (
          <div className="p-md bg-white border-2 border-red-300 rounded-lg shadow-md space-y-sm animate-scale-up">
            <div className="space-y-xxs">
              <h4 className="font-bold text-[13px] text-red-700">Specify Required Changes</h4>
              <p className="text-[11px] text-ink-muted48">The task owner will receive an automated email with this feedback.</p>
            </div>
            <textarea
              required
              rows={3}
              placeholder="e.g. Please update the poster with final sponsor logos and re-upload..."
              value={rejectionInput}
              onChange={(e) => setRejectionInput(e.target.value)}
              className="w-full bg-canvas border border-red-300 rounded-md p-sm text-[12px] text-ink focus:outline-none focus:ring-1 focus:ring-red-500"
            />
            <div className="flex justify-end gap-sm">
              <button
                type="button"
                onClick={() => setIsRejectDialogOpen(false)}
                className="px-md py-[6px] text-[12px] border border-hairline rounded-md hover:bg-ink-muted8"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleConfirmReject}
                className="px-lg py-[6px] text-[12px] bg-red-600 hover:bg-red-700 text-white font-semibold rounded-md shadow-sm"
              >
                Confirm & Send Feedback
              </button>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-sm text-[13px]">
          
          {/* MULTI-DEPARTMENT PROGRESS BREAKDOWN SECTION */}
          {subAssignments.length > 0 && (
            <div className="bg-canvas-parchment/60 border border-hairline rounded-xl p-md space-y-sm">
              <div className="flex items-center justify-between border-b border-hairline pb-xs">
                <div className="flex items-center gap-xs font-bold text-[13px] text-ink">
                  <Sliders className="w-4 h-4 text-primary" />
                  <span>Department Sub-Progress Breakdown</span>
                </div>
                <span className="text-[11px] font-mono font-bold bg-primary/10 text-primary px-sm py-[2px] rounded-pill">
                  Total Aggregate: {progress}%
                </span>
              </div>

              <div className="space-y-sm">
                {subAssignments.map((sub, sIdx) => {
                  const isMySub = sub.assignedTo === myUserId;
                  const isExecutive = role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN';
                  const canEditThisSub = isExecutive || (role === 'LEAD' && sub.teamId === myTeamId) || isMySub;

                  return (
                    <div 
                      key={sIdx}
                      className={`p-sm rounded-lg border transition-all ${
                        isMySub 
                          ? 'bg-primary/5 border-primary/40 shadow-xs' 
                          : 'bg-canvas border-hairline'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-xs">
                        <div className="flex items-center gap-xs">
                          <span className="font-bold text-[12px] text-ink">{sub.teamName || sub.teamId}</span>
                          <span className="text-[11px] text-ink-muted80">👤 {sub.assigneeName || 'Unassigned'}</span>
                          {isMySub && (
                            <span className="bg-primary text-white text-[9px] font-bold px-xs py-[1px] rounded-pill">
                              Your Part
                            </span>
                          )}
                        </div>

                        <select
                          disabled={!canEditThisSub}
                          value={sub.status || 'NOT_STARTED'}
                          onChange={(e) => handleSubStatusChange(sIdx, e.target.value)}
                          className="bg-canvas border border-hairline rounded px-xs py-[3px] text-[11px] font-semibold text-ink focus:outline-none disabled:opacity-60"
                        >
                          <option value="NOT_STARTED">Not Started</option>
                          <option value="IN_PROGRESS">In Progress</option>
                          <option value="VERIFY">Under Verification</option>
                          <option value="BLOCKED">Blocked</option>
                          <option value="COMPLETED">Completed</option>
                        </select>
                      </div>

                      {/* Slider Control */}
                      <div className="space-y-[4px]">
                        <div className="flex items-center justify-between text-[11px] font-mono">
                          <span className="text-ink-muted48">Progress:</span>
                          <span className="font-bold text-ink">{sub.progress || 0}%</span>
                        </div>
                        <input
                          type="range"
                          min="0"
                          max="100"
                          step="5"
                          disabled={!canEditThisSub}
                          value={sub.progress || 0}
                          onChange={(e) => handleSubProgressChange(sIdx, Number(e.target.value))}
                          className="w-full accent-primary h-2 bg-ink-muted8 rounded-lg cursor-pointer disabled:opacity-50"
                        />
                      </div>

                      {canEditThisSub && (
                        <div className="pt-xs mt-xs border-t border-hairline/60">
                          <input
                            type="text"
                            placeholder="Operator note / link for this department..."
                            value={sub.remarks || ''}
                            onChange={(e) => handleSubRemarksChange(sIdx, e.target.value)}
                            className="w-full bg-canvas/60 border border-hairline rounded px-xs py-[4px] text-[11px] focus:outline-none focus:border-primary"
                          />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Section 1: Standard Progress updates (if not multi-department or executive override) */}
          {subAssignments.length === 0 && (
            <div className="bg-canvas-parchment/30 border border-hairline rounded-md p-md space-y-sm">
              <h4 className="text-[11px] font-bold text-primary uppercase tracking-wider">Operator Update</h4>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
                <div className="space-y-xxs">
                  <label className="font-semibold text-caption-strong">Workflow Status</label>
                  <select
                    disabled={!canEditTask}
                    value={status}
                    onChange={(e) => handleStatusChange(e.target.value)}
                    className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                  >
                    <option value="NOT_STARTED">Not Started</option>
                    <option value="IN_PROGRESS">In Progress</option>
                    <option value="VERIFY">Under Verification</option>
                    <option value="DELAYED">Delayed</option>
                    <option value="BLOCKED">Blocked</option>
                    <option value="COMPLETED">Completed</option>
                  </select>
                </div>

                <div className="space-y-xxs">
                  <label className="font-semibold text-caption-strong">Completion Progress (%)</label>
                  <input
                    type="number"
                    min="0"
                    max="100"
                    step="5"
                    disabled={!canEditTask}
                    value={progress}
                    onChange={(e) => handleProgressChange(Number(e.target.value))}
                    className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none font-mono"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Activity Remarks */}
          <div className="space-y-xxs">
            <label className="font-semibold text-caption-strong">Activity Remarks</label>
            <input
              type="text"
              disabled={!canEditTask}
              placeholder="e.g. Updated content drafts & design layout..."
              value={remarks}
              onChange={(e) => setRemarks(e.target.value)}
              className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
            />
          </div>

          {/* Section 2: Administrative Details */}
          <div className="space-y-sm pt-xs border-t border-hairline">
            <h4 className="text-[11px] font-bold text-ink-muted48 uppercase tracking-wider">Task Parameters</h4>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Task Title</label>
              <input
                type="text"
                disabled={!canEditAdminFields}
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
              />
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Description</label>
              <textarea
                disabled={!canEditAdminFields}
                value={desc}
                onChange={(e) => setDesc(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none min-h-[50px]"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Task Deadline</label>
                <input
                  type="date"
                  disabled={!canEditAdminFields}
                  value={deadline}
                  onChange={(e) => setDeadline(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none font-mono"
                />
              </div>

              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Priority</label>
                <select
                  disabled={!canEditAdminFields}
                  value={priority}
                  onChange={(e) => setPriority(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                >
                  <option value="LOW">Low</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="HIGH">High</option>
                  <option value="CRITICAL">Critical</option>
                </select>
              </div>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Assigned Verifier (Approver)</label>
              <select
                disabled={!canEditAdminFields}
                value={verifier}
                onChange={(e) => setVerifier(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
              >
                <option value="">Default (Task Assigner / Lead)</option>
                {users.map(u => (
                  <option key={u.userId} value={u.userId}>
                    {u.name} ({u.role}{u.position ? ` - ${u.position}` : ''})
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Google Drive Asset URL</label>
              <div className="flex items-center gap-xs">
                <input
                  type="url"
                  disabled={!canEditTask}
                  placeholder="https://drive.google.com/..."
                  value={drive}
                  onChange={(e) => setDrive(e.target.value)}
                  className="flex-1 bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                />
                {drive && (
                  <a 
                    href={drive} 
                    target="_blank" 
                    rel="noreferrer"
                    className="p-[8px] bg-ink-muted8 hover:bg-ink-muted16 rounded-md text-primary transition shrink-0"
                    title="Open Google Drive folder"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </a>
                )}
              </div>
            </div>
          </div>

          <div className="flex items-center justify-between gap-sm pt-sm border-t border-hairline">
            {canDeleteTask ? (
              <button
                type="button"
                onClick={() => {
                  if (window.confirm("Are you sure you want to delete this task?")) {
                    onDeleteTask(task.taskId);
                  }
                }}
                className="p-xs text-red-500 hover:bg-red-50 rounded-md transition flex items-center gap-xxs text-[12px]"
              >
                <Trash2 className="w-4 h-4" /> Delete Task
              </button>
            ) : <div></div>}

            <div className="flex items-center gap-sm">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="apple-btn-secondary py-[8px] px-md"
              >
                Cancel
              </button>
              {canEditTask && (
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="apple-btn-primary py-[8px] px-lg"
                >
                  {isSubmitting ? 'Saving...' : 'Save Updates'}
                </button>
              )}
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};
