import React, { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../context/AuthContext';
import { callApi } from '../../services/api';
import { Loading, ErrorState } from '../../components/ui/StateIndicator';
import { 
  Plus, 
  Search,
  Calendar,
  Paperclip,
  TrendingUp,
  X,
  MessageCircle,
  CheckCircle2,
  AlertCircle,
  ShieldCheck,
  RotateCcw,
  Send
} from 'lucide-react';

interface Task {
  taskId: string;
  eventId: string;
  projectId: string;
  taskTitle: string;
  taskDescription: string;
  teamId: string;
  assignedTo: string;
  assignedBy: string;
  verifierId?: string;
  priority: string;
  startDate: string;
  deadline: string;
  status: string;
  completionPercent: number;
  remarks: string;
  rejectionRemarks?: string;
  completionDate: string;
  driveLink: string;
  isAutoGenerated: string;
}

interface Team {
  teamId: string;
  teamName: string;
  teamCode: string;
}

interface User {
  userId: string;
  name: string;
  email: string;
  role: string;
  teamId: string;
  phone?: string;
}

interface EventItem {
  eventId: string;
  eventName: string;
}

const LANES = [
  { id: 'NOT_STARTED', title: 'Not Started', color: 'bg-slate-100 dark:bg-slate-900/40 text-slate-800 dark:text-slate-200 border-slate-200/50' },
  { id: 'IN_PROGRESS', title: 'In Progress', color: 'bg-blue-50/50 dark:bg-blue-950/20 text-blue-800 dark:text-blue-200 border-blue-200/40' },
  { id: 'VERIFY', title: 'Under Verification', color: 'bg-purple-50/50 dark:bg-purple-950/20 text-purple-800 dark:text-purple-200 border-purple-200/40' },
  { id: 'DELAYED', title: 'Delayed', color: 'bg-amber-50/50 dark:bg-amber-950/20 text-amber-800 dark:text-amber-200 border-amber-200/40' },
  { id: 'BLOCKED', title: 'Blocked', color: 'bg-red-50/50 dark:bg-red-950/20 text-red-800 dark:text-red-200 border-red-200/40' },
  { id: 'COMPLETED', title: 'Completed', color: 'bg-green-50/50 dark:bg-green-950/20 text-green-800 dark:text-green-200 border-green-200/40' },
];

export const TaskBoardPage: React.FC = () => {
  const { profile } = useAuth();
  const role = profile?.role || 'MEMBER';
  const myUserId = profile?.userId || '';
  const myTeamId = profile?.teamId || '';
  const queryClient = useQueryClient();

  // Selected Task for detailed view / edit
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);

  // Filters State
  const [filterTeam, setFilterTeam] = useState<string>('');
  const [filterAssignee, setFilterAssignee] = useState<string>('');
  const [filterEvent, setFilterEvent] = useState<string>('');
  const [filterPriority, setFilterPriority] = useState<string>('');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const handleWhatsAppReminder = (e: React.MouseEvent, t: Task) => {
    e.stopPropagation(); // Stop edit modal from triggering
    const user = users.find(u => u.userId === t.assignedTo);
    if (!user) {
      alert("This task is not assigned to any user.");
      return;
    }
    const phone = user.phone ? user.phone.replace(/[^0-9]/g, '') : '';
    if (!phone) {
      const entered = window.prompt(`Enter WhatsApp phone number (with country code, e.g. 919988776655) for ${user.name}:`);
      if (entered) {
        launchWhatsApp(entered, user.name, t);
      }
    } else {
      launchWhatsApp(phone, user.name, t);
    }
  };

  const launchWhatsApp = (phone: string, userName: string, t: Task) => {
    const msg = `Hi ${userName}, just reminding you about your assigned task "${t.taskTitle}" on NEXUS. Priority: ${t.priority}, Deadline: ${t.deadline ? new Date(t.deadline).toLocaleDateString('en-IN') : 'N/A'}. Please update its status on the portal!`;
    const url = `https://api.whatsapp.com/send?phone=${phone}&text=${encodeURIComponent(msg)}`;
    window.open(url, '_blank');
  };

  // Fetch lists
  const { data: tasks = [], isLoading: tasksLoading, error: tasksError, refetch: refetchTasks } = useQuery<Task[]>({
    queryKey: ['tasks'],
    queryFn: () => callApi('tasks.list'),
  });

  const { data: teams = [] } = useQuery<Team[]>({
    queryKey: ['teams'],
    queryFn: () => callApi('teams.list'),
  });

  const { data: users = [] } = useQuery<User[]>({
    queryKey: ['users'],
    queryFn: () => callApi('users.list'),
  });

  const { data: events = [] } = useQuery<EventItem[]>({
    queryKey: ['events'],
    queryFn: () => callApi('events.list'),
  });

  // Direct URL Task Link Handler (?taskId=TSK-XXXX)
  useEffect(() => {
    if (tasks.length > 0) {
      const params = new URLSearchParams(window.location.search);
      const targetTaskId = params.get('taskId');
      if (targetTaskId) {
        const found = tasks.find(t => t.taskId === targetTaskId);
        if (found) {
          setSelectedTask(found);
          setIsEditModalOpen(true);
        }
      }
    }
  }, [tasks]);

  // Mutate task status (optimistic update)
  const updateStatusMutation = useMutation({
    mutationFn: ({ taskId, status, remarks }: { taskId: string; status: string; remarks?: string }) => 
      callApi('tasks.updateStatus', { taskId, status, remarks: remarks || 'Moved lane on Kanban Board.' }),
    onMutate: async ({ taskId, status }) => {
      await queryClient.cancelQueries({ queryKey: ['tasks'] });
      const previousTasks = queryClient.getQueryData<Task[]>(['tasks']);

      if (previousTasks) {
        queryClient.setQueryData<Task[]>(['tasks'], 
          previousTasks.map(t => t.taskId === taskId ? { 
            ...t, 
            status, 
            completionPercent: (status === 'COMPLETED' || status === 'VERIFY') ? 100 : status === 'NOT_STARTED' ? 0 : t.completionPercent 
          } : t)
        );
      }
      return { previousTasks };
    },
    onError: (err, _variables, context) => {
      if (context?.previousTasks) {
        queryClient.setQueryData(['tasks'], context.previousTasks);
      }
      alert(`Failed to update status: ${err instanceof Error ? err.message : 'Unauthorized action'}`);
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    }
  });

  // Mutate update full task fields
  const updateTaskMutation = useMutation({
    mutationFn: ({ taskId, data }: { taskId: string; data: Partial<Task> & { remarks?: string } }) => 
      callApi('tasks.update', { taskId, ...data }),
    onSuccess: () => {
      setIsEditModalOpen(false);
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Failed to update task: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  // Mutate create task
  const createTaskMutation = useMutation({
    mutationFn: (data: Partial<Task>) => callApi('tasks.create', data),
    onSuccess: () => {
      setIsCreateModalOpen(false);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Failed to create task: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  // Mutate Submit for Verification
  const submitVerificationMutation = useMutation({
    mutationFn: ({ taskId, remarks }: { taskId: string; remarks?: string }) =>
      callApi('tasks.submitForVerification', { taskId, remarks: remarks || 'Submitted for verification.' }),
    onSuccess: () => {
      setIsEditModalOpen(false);
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Verification submission failed: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  // Mutate Verify (Approve)
  const verifyMutation = useMutation({
    mutationFn: ({ taskId, remarks }: { taskId: string; remarks?: string }) =>
      callApi('tasks.verify', { taskId, remarks: remarks || 'Verified and approved.' }),
    onSuccess: () => {
      setIsEditModalOpen(false);
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Approval failed: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  // Mutate Reject (Request changes)
  const rejectMutation = useMutation({
    mutationFn: ({ taskId, remarks }: { taskId: string; remarks: string }) =>
      callApi('tasks.reject', { taskId, remarks }),
    onSuccess: () => {
      setIsEditModalOpen(false);
      setSelectedTask(null);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (err) => {
      alert(`Rejection failed: ${err instanceof Error ? err.message : 'Unauthorized'}`);
    }
  });

  // Check if current user can edit administrative fields (reassign, set priority, deadlines)
  const canEditAdminFields = (task: Task) => {
    if (role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN') return true;
    if (role === 'LEAD' && task.teamId === myTeamId) return true;
    return false;
  };

  // Check if current user is authorized to verify/approve/reject task
  const canVerifyTask = (task: Task) => {
    if (role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN') return true;
    if (role === 'LEAD' && task.teamId === myTeamId) return true;
    if (task.verifierId && task.verifierId === myUserId) return true;
    if (task.assignedBy && task.assignedBy === myUserId) return true;
    return false;
  };

  // Drag and Drop implementation
  const handleDragStart = (e: React.DragEvent, task: Task) => {
    e.dataTransfer.setData('text/plain', task.taskId);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = (e: React.DragEvent, targetStatus: string) => {
    e.preventDefault();
    const taskId = e.dataTransfer.getData('text/plain');
    const task = tasks.find(t => t.taskId === taskId);
    if (!task) return;

    // Check status transition permission
    const isAssignedToMe = task.assignedTo === myUserId;
    const isMyTeamLead = role === 'LEAD' && task.teamId === myTeamId;
    const isExecutive = role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN';

    if (isAssignedToMe || isMyTeamLead || isExecutive) {
      updateStatusMutation.mutate({ taskId, status: targetStatus });
    } else {
      alert("Permission denied. You can only update tasks assigned to you or within your team.");
    }
  };

  // Calculations for Metrics Bar
  const today = new Date();
  today.setHours(0,0,0,0);

  const calculateMetrics = () => {
    const activeTasks = tasks.filter(t => t.status !== 'CANCELLED');
    const total = activeTasks.length;
    if (total === 0) return { total: 0, completed: 0, completionRate: 0, delayed: 0, blocked: 0, overdue: 0, verify: 0 };

    const completed = activeTasks.filter(t => t.status === 'COMPLETED').length;
    const verify = activeTasks.filter(t => t.status === 'VERIFY').length;
    const delayed = activeTasks.filter(t => t.status === 'DELAYED').length;
    const blocked = activeTasks.filter(t => t.status === 'BLOCKED').length;

    let overdue = 0;
    activeTasks.forEach(t => {
      if (t.status !== 'COMPLETED' && t.deadline) {
        const deadDate = new Date(t.deadline);
        if (!isNaN(deadDate.getTime()) && deadDate < today) {
          overdue++;
        }
      }
    });

    const completionRate = Math.round((completed / total) * 100);

    return { total, completed, completionRate, delayed, blocked, overdue, verify };
  };

  const metrics = calculateMetrics();

  // Apply filters to tasks list
  const filteredTasks = tasks.filter(task => {
    if (filterTeam && task.teamId !== filterTeam) return false;
    if (filterAssignee && task.assignedTo !== filterAssignee) return false;
    if (filterEvent && task.eventId !== filterEvent) return false;
    if (filterPriority && task.priority !== filterPriority) return false;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      const titleMatch = task.taskTitle?.toLowerCase().includes(q);
      const descMatch = task.taskDescription?.toLowerCase().includes(q);
      const idMatch = task.taskId?.toLowerCase().includes(q);
      if (!titleMatch && !descMatch && !idMatch) return false;
    }
    return true;
  });

  const getPriorityColor = (priority: string) => {
    const p = priority?.toUpperCase() || 'MEDIUM';
    if (p === 'CRITICAL') return 'bg-red-500/10 text-red-700 border-red-200/50';
    if (p === 'HIGH') return 'bg-orange-500/10 text-orange-700 border-orange-200/50';
    if (p === 'MEDIUM') return 'bg-blue-50/80 text-blue-700 border-blue-200/50';
    return 'bg-slate-100 text-slate-600 border-slate-200';
  };

  const isOverdue = (task: Task) => {
    if (task.status === 'COMPLETED') return false;
    if (!task.deadline) return false;
    const deadDate = new Date(task.deadline);
    return !isNaN(deadDate.getTime()) && deadDate < today;
  };

  if (tasksLoading) {
    return <Loading message="Loading Kanban lanes..." />;
  }

  if (tasksError) {
    return (
      <ErrorState 
        title="Failed to load tasks" 
        message={tasksError instanceof Error ? tasksError.message : 'Error communicating with sheet repository.'} 
        onRetry={refetchTasks}
      />
    );
  }

  return (
    <div className="space-y-lg animate-fade-in text-left">
      
      {/* 1. Header with Quick Metrics */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-md">
        <div className="space-y-xxs">
          <span className="text-primary font-semibold text-caption-strong uppercase tracking-wider">Department Board</span>
          <h1 className="text-display-md font-bold text-ink tracking-tight">Task Kanban Board</h1>
          <p className="text-caption-spec text-ink-muted48">Track workloads, verification milestones, and task deliverables.</p>
        </div>
        
        {/* Create Task Action (President, VP, Leads, Admin can create tasks) */}
        {(role === 'PRESIDENT' || role === 'VP' || role === 'ADMIN' || role === 'LEAD') && (
          <button 
            onClick={() => setIsCreateModalOpen(true)}
            className="apple-btn-primary flex items-center justify-center py-[10px] px-lg select-none active:scale-[0.98] transition-all self-start md:self-center"
          >
            <Plus className="w-4 h-4 mr-xs" />
            New Task
          </button>
        )}
      </div>

      {/* 2. Metrics Strip — horizontal scroll on mobile */}
      <div className="overflow-x-auto -mx-lg px-lg sm:mx-0 sm:px-0">
        <div className="flex sm:grid sm:grid-cols-6 min-w-[540px] sm:min-w-0 gap-0 bg-canvas-parchment/60 border border-hairline rounded-lg shadow-inner-soft divide-x divide-hairline">
          <div className="text-center p-sm space-y-xxs flex-1">
            <span className="text-[10px] text-ink-muted48 font-semibold uppercase">Total</span>
            <h3 className="text-body-strong font-bold text-ink">{metrics.total}</h3>
          </div>
          <div className="text-center p-sm space-y-xxs flex-1">
            <span className="text-[10px] text-ink-muted48 font-semibold uppercase">Done %</span>
            <h3 className="text-body-strong font-bold text-green-600 flex items-center justify-center gap-[4px]">
              <TrendingUp className="w-3.5 h-3.5" /> {metrics.completionRate}%
            </h3>
          </div>
          <div className="text-center p-sm space-y-xxs flex-1">
            <span className="text-[10px] text-ink-muted48 font-semibold uppercase">Verify</span>
            <h3 className="text-body-strong font-bold text-purple-600">
              {metrics.verify}
            </h3>
          </div>
          <div className="text-center p-sm space-y-xxs flex-1">
            <span className="text-[10px] text-ink-muted48 font-semibold uppercase">Overdue</span>
            <h3 className={`text-body-strong font-bold ${metrics.overdue > 0 ? 'text-red-500' : 'text-ink'}`}>
              {metrics.overdue}
            </h3>
          </div>
          <div className="text-center p-sm space-y-xxs flex-1">
            <span className="text-[10px] text-ink-muted48 font-semibold uppercase">Delayed</span>
            <h3 className="text-body-strong font-bold text-amber-600">{metrics.delayed}</h3>
          </div>
          <div className="text-center p-sm space-y-xxs flex-1">
            <span className="text-[10px] text-ink-muted48 font-semibold uppercase">Done</span>
            <h3 className="text-body-strong font-bold text-green-700">{metrics.completed}</h3>
          </div>
        </div>
      </div>

      {/* 3. Filters Control Bar */}
      <div className="bg-canvas border border-hairline rounded-lg shadow-product-surface p-md space-y-sm">
        {/* Search */}
        <div className="relative">
          <span className="absolute left-[12px] top-1/2 -translate-y-1/2 text-ink-muted32">
            <Search className="w-4 h-4" />
          </span>
          <input
            type="text"
            placeholder="Search tasks by title, desc, ID..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-canvas border border-hairline rounded-md pl-[36px] pr-sm py-[9px] text-[13px] text-ink placeholder-ink-muted32 focus:border-primary focus:ring-1 focus:ring-primary focus:outline-none transition"
          />
        </div>

        {/* Filter dropdowns */}
        <div className="flex flex-wrap items-center gap-sm">
          {/* Team filter */}
          <select
            value={filterTeam}
            onChange={(e) => setFilterTeam(e.target.value)}
            className="flex-1 min-w-[110px] bg-canvas border border-hairline rounded-md px-sm py-[8px] text-[13px] text-ink focus:border-primary focus:outline-none"
          >
            <option value="">All Teams</option>
            {teams.map(t => (
              <option key={t.teamId} value={t.teamId}>{t.teamName}</option>
            ))}
          </select>

          {/* Assignee filter */}
          <select
            value={filterAssignee}
            onChange={(e) => setFilterAssignee(e.target.value)}
            className="flex-1 min-w-[120px] bg-canvas border border-hairline rounded-md px-sm py-[8px] text-[13px] text-ink focus:border-primary focus:outline-none"
          >
            <option value="">All Members</option>
            <option value={myUserId}>Assigned to Me</option>
            {users.map(u => (
              <option key={u.userId} value={u.userId}>{u.name}</option>
            ))}
          </select>

          {/* Priority filter */}
          <select
            value={filterPriority}
            onChange={(e) => setFilterPriority(e.target.value)}
            className="flex-1 min-w-[100px] bg-canvas border border-hairline rounded-md px-sm py-[8px] text-[13px] text-ink focus:border-primary focus:outline-none"
          >
            <option value="">All Priority</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          {/* Event filter */}
          <select
            value={filterEvent}
            onChange={(e) => setFilterEvent(e.target.value)}
            className="flex-1 min-w-[120px] bg-canvas border border-hairline rounded-md px-sm py-[8px] text-[13px] text-ink focus:border-primary focus:outline-none"
          >
            <option value="">All Events</option>
            {events.map(ev => (
              <option key={ev.eventId} value={ev.eventId}>{ev.eventName}</option>
            ))}
          </select>

          {/* Reset Filters button */}
          {(filterTeam || filterAssignee || filterEvent || filterPriority || searchQuery) && (
            <button 
              onClick={() => {
                setFilterTeam('');
                setFilterAssignee('');
                setFilterEvent('');
                setFilterPriority('');
                setSearchQuery('');
              }}
              className="text-[12px] text-primary font-semibold hover:underline whitespace-nowrap"
            >
              Reset Filters
            </button>
          )}
        </div>
      </div>

      {/* 4. Kanban lanes board */}
      <div className="overflow-x-auto -mx-lg px-lg sm:-mx-xl sm:px-xl md:mx-0 md:px-0 pb-lg">
        <div className="flex md:grid md:grid-cols-3 lg:grid-cols-6 gap-md min-w-[1100px] md:min-w-0 select-none snap-x snap-mandatory md:snap-none">
          {LANES.map(lane => {
            // In Progress lane also hosts tasks marked REJECTED (needs changes)
            const laneTasks = filteredTasks.filter(t => {
              if (lane.id === 'IN_PROGRESS') {
                return t.status === 'IN_PROGRESS' || t.status === 'REJECTED';
              }
              return t.status === lane.id;
            });
            
            return (
              <div 
                key={lane.id}
                onDragOver={handleDragOver}
                onDrop={(e) => handleDrop(e, lane.id)}
                className="flex flex-col w-[240px] md:w-auto flex-shrink-0 md:flex-shrink bg-canvas-parchment/30 border border-hairline rounded-lg shadow-inner-soft p-sm min-h-[420px] snap-start"
              >
                {/* Lane Header */}
                <div className={`px-sm py-xxs border rounded-pill flex items-center justify-between font-text text-[12px] font-semibold mb-sm ${lane.color}`}>
                  <span>{lane.title}</span>
                  <span className="w-5 h-5 rounded-full bg-canvas border border-hairline flex items-center justify-center text-[10px] text-ink font-bold">
                    {laneTasks.length}
                  </span>
                </div>

                {/* Lane Cards Container */}
                <div className="flex-1 space-y-sm overflow-y-auto max-h-[600px] scrollbar-thin">
                  {laneTasks.length === 0 ? (
                    <div className="h-full border border-dashed border-hairline rounded-md flex items-center justify-center py-xl text-caption-spec text-ink-muted32">
                      Drop items here
                    </div>
                  ) : (
                    laneTasks.map(task => {
                      const assigneeName = users.find(u => u.userId === task.assignedTo)?.name || 'Unassigned';
                      const eventName = events.find(e => e.eventId === task.eventId)?.eventName || '';
                      const taskOverdue = isOverdue(task);
                      const isRejected = task.status === 'REJECTED';
                      const isUnderVerification = task.status === 'VERIFY';

                      return (
                        <div
                          key={task.taskId}
                          draggable
                          onDragStart={(e) => handleDragStart(e, task)}
                          onClick={() => {
                            setSelectedTask(task);
                            setIsEditModalOpen(true);
                          }}
                          className={`bg-canvas border rounded-md p-md shadow-product-surface space-y-xs cursor-pointer hover:border-primary hover:shadow-md transition-all active:scale-[0.98] text-left ${
                            isRejected 
                              ? 'border-red-300 bg-red-50/20' 
                              : isUnderVerification 
                              ? 'border-purple-300 bg-purple-50/20' 
                              : 'border-hairline'
                          }`}
                        >
                          <div className="flex items-start justify-between gap-xs">
                            <span className="text-[10px] font-mono text-ink-muted32 font-bold">{task.taskId}</span>
                            <div className="flex items-center gap-[4px]">
                              {isRejected && (
                                <span className="px-xxs py-[1px] text-[8.5px] font-bold bg-red-100 text-red-700 rounded-sm">
                                  Changes Needed
                                </span>
                              )}
                              {isUnderVerification && (
                                <span className="px-xxs py-[1px] text-[8.5px] font-bold bg-purple-100 text-purple-700 rounded-sm">
                                  Under Review
                                </span>
                              )}
                              <span className={`px-xxs py-[1px] text-[9px] font-semibold border rounded-sm uppercase tracking-wider font-mono ${getPriorityColor(task.priority)}`}>
                                {task.priority}
                              </span>
                            </div>
                          </div>

                          <div className="space-y-xxs">
                            <h4 className="text-[13px] font-bold text-ink leading-tight line-clamp-2">{task.taskTitle}</h4>
                            {task.taskDescription && (
                              <p className="text-[11px] text-ink-muted48 line-clamp-2 leading-relaxed">{task.taskDescription}</p>
                            )}
                          </div>

                          {/* Rejection Note if present */}
                          {isRejected && task.rejectionRemarks && (
                            <div className="p-xs bg-red-50 border border-red-200 rounded text-[10px] text-red-700 leading-snug">
                              <strong>Feedback:</strong> {task.rejectionRemarks}
                            </div>
                          )}

                          {/* Progress */}
                          <div className="space-y-xxs pt-xxs">
                            <div className="flex items-center justify-between text-[10px] text-ink-muted48 font-mono">
                              <span>Progress</span>
                              <span>{task.completionPercent || 0}%</span>
                            </div>
                            <div className="w-full bg-ink-muted8 h-[4px] rounded-full overflow-hidden">
                              <div 
                                className={`h-full rounded-full transition-all duration-300 ${
                                  task.status === 'COMPLETED' ? 'bg-green-500' : isUnderVerification ? 'bg-purple-500' : 'bg-primary'
                                }`} 
                                style={{ width: `${task.completionPercent || 0}%` }}
                              ></div>
                            </div>
                          </div>

                          <div className="border-t border-hairline pt-xxs flex items-center justify-between text-[10px] text-ink-muted48">
                            <span className="truncate max-w-[100px] flex items-center gap-xxs" title={`Assignee: ${assigneeName}`}>
                              👤 {assigneeName}
                              {task.assignedTo && (
                                <button 
                                  onClick={(e) => handleWhatsAppReminder(e, task)}
                                  title="Remind via WhatsApp"
                                  className="p-[2px] hover:bg-green-50 text-green-600 rounded transition shrink-0"
                                >
                                  <MessageCircle className="w-3.5 h-3.5" />
                                </button>
                              )}
                            </span>
                            
                            {task.deadline && (
                              <span className={`flex items-center gap-[2px] font-mono ${
                                taskOverdue ? 'text-red-500 font-semibold' : ''
                              }`}>
                                <Calendar className="w-3 h-3" />
                                {new Date(task.deadline).toLocaleDateString('en-IN', { month: 'short', day: 'numeric' })}
                              </span>
                            )}
                          </div>

                          {eventName && (
                            <div className="text-[9px] text-primary bg-primary/5 px-xxs py-[2px] rounded-sm truncate" title={`Event: ${eventName}`}>
                              🎯 {eventName}
                            </div>
                          )}
                          {task.driveLink && (
                            <div className="flex items-center gap-xxs text-[9px] text-ink-muted48">
                              <Paperclip className="w-2.5 h-2.5" /> Google Drive Link
                            </div>
                          )}
                        </div>
                      );
                    })
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* 5. Create Task Modal */}
      {isCreateModalOpen && (
        <CreateTaskModal 
          teams={teams}
          users={users}
          events={events}
          onSubmit={(data) => createTaskMutation.mutate(data)}
          onClose={() => setIsCreateModalOpen(false)}
        />
      )}

      {/* 6. Edit / View Task Modal */}
      {isEditModalOpen && selectedTask && (
        <EditTaskModal 
          task={selectedTask}
          teams={teams}
          users={users}
          events={events}
          myUserId={myUserId}
          canEditAdminFields={canEditAdminFields(selectedTask)}
          canVerifyTask={canVerifyTask(selectedTask)}
          onSubmit={(taskId, data) => updateTaskMutation.mutate({ taskId, data })}
          onSubmitForVerification={(taskId, remarks) => submitVerificationMutation.mutate({ taskId, remarks })}
          onVerify={(taskId, remarks) => verifyMutation.mutate({ taskId, remarks })}
          onReject={(taskId, remarks) => rejectMutation.mutate({ taskId, remarks })}
          isSubmitting={updateTaskMutation.isPending || submitVerificationMutation.isPending || verifyMutation.isPending || rejectMutation.isPending}
          onClose={() => {
            setIsEditModalOpen(false);
            setSelectedTask(null);
          }}
        />
      )}

    </div>
  );
};

/* --- CREATE TASK MODAL COMPONENT --- */
interface CreateModalProps {
  teams: Team[];
  users: User[];
  events: EventItem[];
  onSubmit: (data: Partial<Task>) => void;
  onClose: () => void;
}
const CreateTaskModal: React.FC<CreateModalProps> = ({ teams, users, events, onSubmit, onClose }) => {
  const [title, setTitle] = useState('');
  const [desc, setDesc] = useState('');
  const [team, setTeam] = useState('');
  const [assignee, setAssignee] = useState('');
  const [priority, setPriority] = useState('MEDIUM');
  const [deadline, setDeadline] = useState('');
  const [eventVal, setEventVal] = useState('');
  const [drive, setDrive] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) {
      alert("Title is required!");
      return;
    }
    onSubmit({
      taskTitle: title,
      taskDescription: desc,
      teamId: team,
      assignedTo: assignee,
      priority,
      deadline: deadline || undefined,
      eventId: eventVal,
      driveLink: drive
    });
  };

  return (
    <div className="fixed inset-0 bg-canvas/60 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center sm:p-md select-none font-text text-ink">
      <div className="bg-canvas border border-hairline sm:rounded-lg rounded-t-xl shadow-product-surface max-w-[480px] w-full p-lg space-y-md animate-scale-up text-left max-h-[90dvh] overflow-y-auto">
        <div className="flex items-center justify-between border-b border-hairline pb-xs">
          <h3 className="text-body-strong font-bold text-ink">Initialize Operations Task</h3>
          <button onClick={onClose} className="p-xxs hover:bg-ink-muted8 rounded-md transition">
            <X className="w-4 h-4 text-ink-muted48 hover:text-ink" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-sm text-[13px]">
          <div className="space-y-xxs">
            <label className="font-semibold text-caption-strong">Task Title *</label>
            <input
              type="text"
              required
              placeholder="e.g. Confirm Hackathon catering count"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
            />
          </div>

          <div className="space-y-xxs">
            <label className="font-semibold text-caption-strong">Description</label>
            <textarea
              placeholder="Provide scope details..."
              value={desc}
              onChange={(e) => setDesc(e.target.value)}
              className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink focus:border-primary focus:outline-none min-h-[60px]"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Assign Team</label>
              <select
                value={team}
                onChange={(e) => {
                  setTeam(e.target.value);
                  setAssignee('');
                }}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="">Unassigned Team</option>
                {teams.map(t => (
                  <option key={t.teamId} value={t.teamId}>{t.teamName}</option>
                ))}
              </select>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Assign User</label>
              <select
                value={assignee}
                onChange={(e) => setAssignee(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="">Unassigned User</option>
                {users
                  .filter(u => !team || u.teamId === team)
                  .map(u => (
                    <option key={u.userId} value={u.userId}>{u.name}</option>
                  ))
                }
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Priority</label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="LOW">Low</option>
                <option value="MEDIUM">Medium</option>
                <option value="HIGH">High</option>
                <option value="CRITICAL">Critical</option>
              </select>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Task Deadline</label>
              <input
                type="date"
                value={deadline}
                onChange={(e) => setDeadline(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink focus:border-primary focus:outline-none font-mono"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Target Event</label>
              <select
                value={eventVal}
                onChange={(e) => setEventVal(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              >
                <option value="">None</option>
                {events.map(ev => (
                  <option key={ev.eventId} value={ev.eventId}>{ev.eventName}</option>
                ))}
              </select>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Google Drive Asset URL</label>
              <input
                type="url"
                placeholder="https://drive.google.com/..."
                value={drive}
                onChange={(e) => setDrive(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              />
            </div>
          </div>

          <div className="flex justify-end gap-sm pt-xs border-t border-hairline">
            <button
              type="button"
              onClick={onClose}
              className="apple-btn-secondary py-[8px] px-md select-none active:scale-[0.98] transition"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="apple-btn-primary py-[8px] px-lg select-none active:scale-[0.98] transition"
            >
              Initialize Task
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

/* --- EDIT / VIEW TASK MODAL COMPONENT --- */
interface EditModalProps {
  task: Task;
  teams: Team[];
  users: User[];
  events: EventItem[];
  myUserId: string;
  canEditAdminFields: boolean;
  canVerifyTask: boolean;
  onSubmit: (taskId: string, data: Partial<Task> & { remarks?: string }) => void;
  onSubmitForVerification: (taskId: string, remarks?: string) => void;
  onVerify: (taskId: string, remarks?: string) => void;
  onReject: (taskId: string, remarks: string) => void;
  isSubmitting: boolean;
  onClose: () => void;
}

const EditTaskModal: React.FC<EditModalProps> = ({ 
  task, 
  teams, 
  users, 
  events, 
  myUserId,
  canEditAdminFields, 
  canVerifyTask,
  onSubmit, 
  onSubmitForVerification,
  onVerify,
  onReject,
  isSubmitting,
  onClose 
}) => {
  // Operational fields
  const [status, setStatus] = useState(task.status);
  const [progress, setProgress] = useState<number>(task.completionPercent || 0);
  const [remarks, setRemarks] = useState('');

  // Rejection dialog state
  const [isRejectDialogOpen, setIsRejectDialogOpen] = useState(false);
  const [rejectionInput, setRejectionInput] = useState('');

  // Administrative restricted fields
  const [title, setTitle] = useState(task.taskTitle);
  const [desc, setDesc] = useState(task.taskDescription || '');
  const [team, setTeam] = useState(task.teamId || '');
  const [assignee, setAssignee] = useState(task.assignedTo || '');
  const [priority, setPriority] = useState(task.priority);
  const [deadline, setDeadline] = useState(task.deadline ? new Date(task.deadline).toISOString().split('T')[0] : '');
  const [eventVal, setEventVal] = useState(task.eventId || '');
  const [drive, setDrive] = useState(task.driveLink || '');

  const isOwner = task.assignedTo === myUserId;
  const isUnderVerification = task.status === 'VERIFY';
  const isRejected = task.status === 'REJECTED';

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const payload: any = {
      status,
      completionPercent: Number(progress),
      remarks: remarks || 'Task modified.'
    };

    if (canEditAdminFields) {
      payload.taskTitle = title;
      payload.taskDescription = desc;
      payload.teamId = team;
      payload.assignedTo = assignee;
      payload.priority = priority;
      payload.deadline = deadline || null;
      payload.eventId = eventVal;
      payload.driveLink = drive;
    }

    onSubmit(task.taskId, payload);
  };

  const handleStatusChange = (newStatus: string) => {
    setStatus(newStatus);
    if (newStatus === 'COMPLETED' || newStatus === 'VERIFY') {
      setProgress(100);
    } else if (newStatus === 'NOT_STARTED') {
      setProgress(0);
    }
  };

  const handleProgressChange = (newProgress: number) => {
    setProgress(newProgress);
    if (newProgress === 100) {
      if (status !== 'VERIFY') setStatus('COMPLETED');
    } else if (task.status === 'COMPLETED' && newProgress < 100) {
      setStatus(newProgress === 0 ? 'NOT_STARTED' : 'IN_PROGRESS');
    }
  };

  const handleConfirmReject = (e: React.FormEvent) => {
    e.preventDefault();
    if (!rejectionInput.trim()) {
      alert("Please provide feedback or the reason changes are required.");
      return;
    }
    onReject(task.taskId, rejectionInput.trim());
    setIsRejectDialogOpen(false);
  };

  return (
    <div className="fixed inset-0 bg-canvas/60 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center sm:p-md select-none font-text text-ink">
      <div className="bg-canvas border border-hairline sm:rounded-lg rounded-t-xl shadow-product-surface max-w-[540px] w-full p-lg space-y-md animate-scale-up text-left max-h-[92dvh] overflow-y-auto">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-hairline pb-xs">
          <div className="space-y-[2px]">
            <span className="text-[10px] font-mono text-ink-muted48 uppercase">Task ID: {task.taskId}</span>
            <h3 className="text-body-strong font-bold text-ink flex items-center gap-xs">
              {task.taskTitle}
            </h3>
          </div>
          <button onClick={onClose} className="p-xxs hover:bg-ink-muted8 rounded-md transition">
            <X className="w-4 h-4 text-ink-muted48 hover:text-ink" />
          </button>
        </div>

        {/* 🚨 Rejection Feedback Banner if changes requested */}
        {isRejected && task.rejectionRemarks && (
          <div className="p-md bg-red-50 border border-red-200 rounded-lg space-y-xxs animate-fade-in text-red-800">
            <div className="flex items-center gap-xs font-bold text-[13px] text-red-700">
              <AlertCircle className="w-4 h-4 text-red-600" />
              <span>Changes Requested by Verifier</span>
            </div>
            <p className="text-[12px] text-red-900 leading-relaxed pl-[20px]">
              "{task.rejectionRemarks}"
            </p>
          </div>
        )}

        {/* 🔍 Verification Action Panel for Authorized Verifiers */}
        {isUnderVerification && canVerifyTask && (
          <div className="p-md bg-purple-50 border border-purple-200 rounded-lg space-y-sm animate-fade-in">
            <div className="flex items-center gap-xs font-bold text-[13px] text-purple-900">
              <ShieldCheck className="w-4 h-4 text-purple-700" />
              <span>Verification Review Required</span>
            </div>
            <p className="text-[12px] text-purple-800 leading-relaxed">
              This task was completed and submitted for your approval. Please inspect the deliverables.
            </p>
            <div className="flex flex-wrap items-center gap-sm pt-xxs">
              <button
                type="button"
                disabled={isSubmitting}
                onClick={() => onVerify(task.taskId, "Verified and approved on task board.")}
                className="flex-1 apple-btn-primary bg-green-600 hover:bg-green-700 text-[12px] py-[8px] flex items-center justify-center gap-xs shadow-sm"
              >
                <CheckCircle2 className="w-4 h-4" />
                Approve & Complete
              </button>
              <button
                type="button"
                disabled={isSubmitting}
                onClick={() => setIsRejectDialogOpen(true)}
                className="flex-1 bg-white border border-red-300 text-red-700 hover:bg-red-50 text-[12px] font-semibold py-[8px] px-md rounded-pill flex items-center justify-center gap-xs transition shadow-sm"
              >
                <RotateCcw className="w-4 h-4" />
                Request Changes
              </button>
            </div>
          </div>
        )}

        {/* 🚀 Submit for Verification Button for Task Owner */}
        {(!isUnderVerification && task.status !== 'COMPLETED') && (isOwner || canEditAdminFields) && (
          <div className="p-sm bg-blue-50/60 border border-blue-200 rounded-lg flex items-center justify-between gap-sm">
            <div className="space-y-[2px]">
              <span className="text-[12px] font-bold text-blue-900">Finished your work?</span>
              <p className="text-[11px] text-blue-700">Submit task to lead/verifier for approval.</p>
            </div>
            <button
              type="button"
              disabled={isSubmitting}
              onClick={() => {
                const note = window.prompt("Add an optional progress note for the verifier:", remarks || "Deliverables ready.");
                if (note !== null) {
                  onSubmitForVerification(task.taskId, note);
                }
              }}
              className="apple-btn-primary bg-primary hover:bg-primary-focus text-[12px] py-[7px] px-md flex items-center gap-xs shrink-0 shadow-sm"
            >
              <Send className="w-3.5 h-3.5" />
              Submit for Verification
            </button>
          </div>
        )}

        {/* Reject Dialog Popover */}
        {isRejectDialogOpen && (
          <div className="p-md bg-white border-2 border-red-300 rounded-lg shadow-md space-y-sm animate-scale-up">
            <div className="space-y-xxs">
              <h4 className="font-bold text-[13px] text-red-700">Specify Required Changes</h4>
              <p className="text-[11px] text-ink-muted48">The task owner will receive an automated email with this feedback.</p>
            </div>
            <textarea
              required
              rows={3}
              placeholder="e.g. Please update the poster with final sponsor logos and re-upload..."
              value={rejectionInput}
              onChange={(e) => setRejectionInput(e.target.value)}
              className="w-full bg-canvas border border-red-300 rounded-md p-sm text-[12px] text-ink focus:outline-none focus:ring-1 focus:ring-red-500"
            />
            <div className="flex justify-end gap-sm">
              <button
                type="button"
                onClick={() => setIsRejectDialogOpen(false)}
                className="px-md py-[6px] text-[12px] border border-hairline rounded-md hover:bg-ink-muted8"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleConfirmReject}
                className="px-lg py-[6px] text-[12px] bg-red-600 hover:bg-red-700 text-white font-semibold rounded-md shadow-sm"
              >
                Confirm & Send Feedback
              </button>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-sm text-[13px]">
          
          {/* Section 1: Standard Progress updates */}
          <div className="bg-canvas-parchment/30 border border-hairline rounded-md p-md space-y-sm">
            <h4 className="text-[11px] font-bold text-primary uppercase tracking-wider">Operator Update</h4>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Workflow Status</label>
                <select
                  value={status}
                  onChange={(e) => handleStatusChange(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
                >
                  <option value="NOT_STARTED">Not Started</option>
                  <option value="IN_PROGRESS">In Progress</option>
                  <option value="VERIFY">Under Verification</option>
                  <option value="DELAYED">Delayed</option>
                  <option value="BLOCKED">Blocked</option>
                  <option value="COMPLETED">Completed</option>
                </select>
              </div>

              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Completion Progress (%)</label>
                <input
                  type="number"
                  min="0"
                  max="100"
                  step="5"
                  value={progress}
                  onChange={(e) => handleProgressChange(Number(e.target.value))}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none font-mono"
                />
              </div>
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Operator Activity Remarks *</label>
              <input
                type="text"
                required
                placeholder="Remarks are required to commit status changes..."
                value={remarks}
                onChange={(e) => setRemarks(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink focus:border-primary focus:outline-none"
              />
            </div>
          </div>

          {/* Section 2: Administrative Details (Read Only for general members, editable by Lead/President/Admin) */}
          <div className="space-y-sm">
            <h4 className="text-[11px] font-bold text-ink-muted48 uppercase tracking-wider">Task Parameters</h4>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Task Title</label>
              <input
                type="text"
                disabled={!canEditAdminFields}
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
              />
            </div>

            <div className="space-y-xxs">
              <label className="font-semibold text-caption-strong">Description</label>
              <textarea
                disabled={!canEditAdminFields}
                value={desc}
                onChange={(e) => setDesc(e.target.value)}
                className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none min-h-[50px]"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Assign Team</label>
                <select
                  disabled={!canEditAdminFields}
                  value={team}
                  onChange={(e) => {
                    setTeam(e.target.value);
                    setAssignee('');
                  }}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                >
                  <option value="">Unassigned</option>
                  {teams.map(t => (
                    <option key={t.teamId} value={t.teamId}>{t.teamName}</option>
                  ))}
                </select>
              </div>

              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Assign User</label>
                <select
                  disabled={!canEditAdminFields}
                  value={assignee}
                  onChange={(e) => setAssignee(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                >
                  <option value="">Unassigned</option>
                  {users
                    .filter(u => !team || u.teamId === team)
                    .map(u => (
                      <option key={u.userId} value={u.userId}>{u.name}</option>
                    ))
                  }
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Priority</label>
                <select
                  disabled={!canEditAdminFields}
                  value={priority}
                  onChange={(e) => setPriority(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                >
                  <option value="LOW">Low</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="HIGH">High</option>
                  <option value="CRITICAL">Critical</option>
                </select>
              </div>

              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Task Deadline</label>
                <input
                  type="date"
                  disabled={!canEditAdminFields}
                  value={deadline}
                  onChange={(e) => setDeadline(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[6px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none font-mono"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-sm">
              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Target Event</label>
                <select
                  disabled={!canEditAdminFields}
                  value={eventVal}
                  onChange={(e) => setEventVal(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                >
                  <option value="">None</option>
                  {events.map(ev => (
                    <option key={ev.eventId} value={ev.eventId}>{ev.eventName}</option>
                  ))}
                </select>
              </div>

              <div className="space-y-xxs">
                <label className="font-semibold text-caption-strong">Drive Link</label>
                <input
                  type="url"
                  disabled={!canEditAdminFields}
                  placeholder="https://drive.google.com/..."
                  value={drive}
                  onChange={(e) => setDrive(e.target.value)}
                  className="w-full bg-canvas border border-hairline rounded-md px-sm py-[8px] text-ink disabled:bg-ink-muted4 disabled:text-ink-muted48 focus:border-primary focus:outline-none"
                />
              </div>
            </div>
          </div>

          <div className="flex justify-end gap-sm pt-xs border-t border-hairline">
            <button
              type="button"
              onClick={onClose}
              className="apple-btn-secondary py-[8px] px-md select-none active:scale-[0.98] transition"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="apple-btn-primary py-[8px] px-lg select-none active:scale-[0.98] transition"
            >
              Commit Changes
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
