// EventsHandler.gs — Core handlers for Events management (03_Events sheet).

/**
 * Returns all active events.
 * @returns {Array<Object>} List of active events
 */
function handleListEvents() {
  var repo = new SheetRepository("03_Events", "EVT", "eventId");
  return repo.getAll();
}

/**
 * Retrieves details for a single event by ID.
 * @param {string} eventId - Unique ID of the event
 * @returns {Object} The event details
 */
function handleGetEvent(eventId) {
  if (!eventId) {
    throw new Error("Missing event ID.");
  }
  var repo = new SheetRepository("03_Events", "EVT", "eventId");
  var eventRecord = repo.getById(eventId);
  if (!eventRecord) {
    throw new Error("Event not found with ID: " + eventId);
  }
  return eventRecord;
}

/**
 * Creates a new event record. Instantiates template-driven tasks if applicable.
 * @param {Object} eventData - Event parameters
 * @param {string} creatorUserId - User ID of the event creator
 * @returns {Object} The newly created event record
 */
function handleCreateEvent(eventData, creatorUserId) {
  if (!eventData || !eventData.eventName || !eventData.eventDate) {
    throw new Error("Invalid payload: eventName and eventDate are required.");
  }

  var eventDateObj = new Date(eventData.eventDate);
  if (isNaN(eventDateObj.getTime())) {
    throw new Error("Invalid eventDate format: " + eventData.eventDate);
  }

  var eventsRepo = new SheetRepository("03_Events", "EVT", "eventId");
  
  var newEvent = {
    eventName: eventData.eventName,
    eventCategory: eventData.eventCategory || "WORKSHOP",
    eventDescription: eventData.eventDescription || "",
    eventDate: eventDateObj,
    venue: eventData.venue || "",
    leadTeamId: eventData.leadTeamId || "",
    budgetAllocation: Number(eventData.budgetAllocation) || 0,
    eventStatus: "PLANNING",
    driveFolderId: eventData.driveFolderId || "",
    remarks: eventData.remarks || "",
    isTemplateDriven: String(eventData.isTemplateDriven).toUpperCase() === "TRUE" ? "TRUE" : "FALSE",
    sourceTemplateId: eventData.sourceTemplateId || "",
    createdBy: creatorUserId || ""
  };

  var insertedEvent = eventsRepo.insert(newEvent);
  var eventId = insertedEvent.eventId;
  Logger.log("Created Event: " + eventId);

  // Log Audit trail
  logAudit(creatorUserId, "events.create", "Events", eventId, "", insertedEvent, "SUCCESS");

  // If template-driven, auto-instantiate the template tasks
  if (insertedEvent.isTemplateDriven === "TRUE" && insertedEvent.sourceTemplateId) {
    var templatesRepo = new SheetRepository("20_Event_Templates", null, "templateId");
    var templateTasks = templatesRepo.find({ templateId: insertedEvent.sourceTemplateId });
    
    if (templateTasks.length > 0) {
      var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
      Logger.log("Instantiating " + templateTasks.length + " template tasks for Event: " + eventId);
      
      for (var i = 0; i < templateTasks.length; i++) {
        var templateTask = templateTasks[i];
        
        // Calculate offset deadline relative to eventDate
        var offsetDays = parseInt(templateTask.dayOffset, 10) || 0;
        var taskDeadline = new Date(eventDateObj.getTime());
        taskDeadline.setDate(eventDateObj.getDate() + offsetDays);
        
        var taskRecord = {
          eventId: eventId,
          projectId: "",
          taskTitle: templateTask.taskTitle,
          taskDescription: templateTask.taskDescription || "",
          teamId: templateTask.teamId || "",
          assignedTo: "", // Initially unassigned
          assignedBy: creatorUserId || "",
          priority: templateTask.defaultPriority || "MEDIUM",
          startDate: new Date(),
          deadline: taskDeadline,
          status: "NOT_STARTED",
          completionPercent: 0,
          remarks: "",
          completionDate: "",
          driveLink: "",
          isAutoGenerated: "TRUE",
          sourceTemplateId: insertedEvent.sourceTemplateId
        };
        
        tasksRepo.insert(taskRecord);
      }
      Logger.log("Task instantiation complete.");
    }
  }

  return insertedEvent;
}

/**
 * Updates an event's details. If status is updated to CANCELLED, cascades to tasks.
 * @param {string} eventId - Unique ID of the event to update
 * @param {Object} eventData - Fields to update
 * @returns {Object} The updated event record
 */
function handleUpdateEvent(eventId, eventData, operatorUserId) {
  if (!eventId || !eventData) {
    throw new Error("Missing event ID or update payload.");
  }

  var eventsRepo = new SheetRepository("03_Events", "EVT", "eventId");
  var existingEvent = eventsRepo.getById(eventId);
  if (!existingEvent) {
    throw new Error("Event not found with ID: " + eventId);
  }
  
  var updateFields = {};
  if (eventData.hasOwnProperty("eventName")) updateFields.eventName = eventData.eventName;
  if (eventData.hasOwnProperty("eventDescription")) updateFields.eventDescription = eventData.eventDescription;
  if (eventData.hasOwnProperty("eventDate")) {
    var dObj = new Date(eventData.eventDate);
    if (!isNaN(dObj.getTime())) {
      updateFields.eventDate = dObj;
    }
  }
  if (eventData.hasOwnProperty("venue")) updateFields.venue = eventData.venue;
  if (eventData.hasOwnProperty("budgetAllocation")) updateFields.budgetAllocation = Number(eventData.budgetAllocation) || 0;
  if (eventData.hasOwnProperty("remarks")) updateFields.remarks = eventData.remarks;
  if (eventData.hasOwnProperty("driveFolderId")) updateFields.driveFolderId = eventData.driveFolderId;
  
  if (eventData.hasOwnProperty("eventStatus")) {
    updateFields.eventStatus = eventData.eventStatus.toUpperCase();
  }

  var updatedEvent = eventsRepo.update(eventId, updateFields);
  
  // Log Audit trail
  var actionName = updateFields.eventStatus === "CANCELLED" ? "events.cancel" : "events.update";
  logAudit(operatorUserId, actionName, "Events", eventId, existingEvent, updatedEvent, "SUCCESS");

  // Cascade cancellation to tasks if the status was changed to CANCELLED
  if (updateFields.eventStatus === "CANCELLED") {
    cascadeEventCancellation(eventId);
  }

  return updatedEvent;
}

/**
 * Cancels an event and its uncompleted tasks.
 * @param {string} eventId - Unique ID of the event to cancel
 * @param {string} operatorUserId - User ID of the operator
 * @returns {Object} The cancelled event record
 */
function handleCancelEvent(eventId, operatorUserId) {
  return handleUpdateEvent(eventId, { eventStatus: "CANCELLED" }, operatorUserId);
}

/**
 * Deletes an event and its uncompleted tasks.
 * @param {string} eventId - Unique ID of the event to delete
 * @param {string} operatorUserId - User ID of the operator
 * @returns {Object} The deleted event record
 */
function handleDeleteEvent(eventId, operatorUserId) {
  if (!eventId) throw new Error("Missing event ID.");
  var eventsRepo = new SheetRepository("03_Events", "EVT", "eventId");
  var existingEvent = eventsRepo.getById(eventId);
  if (!existingEvent) throw new Error("Event not found with ID: " + eventId);

  var deleted = eventsRepo.delete(eventId);
  cascadeEventCancellation(eventId);
  logAudit(operatorUserId, "events.delete", "Events", eventId, existingEvent, deleted, "SUCCESS");
  return deleted;
}

/**
 * Helper to cascade cancellation to all uncompleted tasks for a given event.
 * @param {string} eventId - Unique ID of the cancelled event
 */
function cascadeEventCancellation(eventId) {
  Logger.log("Cascading cancellation to all tasks for Event: " + eventId);
  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var rawTasks = tasksRepo._getData().rows;
  
  var cancelledCount = 0;
  for (var i = 0; i < rawTasks.length; i++) {
    var task = rawTasks[i];
    if (task.eventId === eventId) {
      var status = String(task.status || '').toUpperCase();
      if (status !== "CANCELLED") {
        tasksRepo.update(task.taskId, { status: "CANCELLED" });
        cancelledCount++;
      }
    }
  }
  Logger.log("Cascaded cancellation to " + cancelledCount + " tasks.");
}
