// Setup.gs — Spreadsheet initialization and schema enforcement.
// Contains setupNexusSpreadsheet() to build the database from scratch idempotently.

/**
 * Main entry point for spreadsheet initialization.
 * Creates all 22 tabs, sets up headers, formats columns, adds dropdown validations,
 * configures status conditional formatting, and protects administrative ranges.
 */
function setupNexusSpreadsheet() {
  var ss;
  
  // 1. Get or create spreadsheet
  if (typeof SPREADSHEET_ID !== 'undefined' && SPREADSHEET_ID) {
    try {
      ss = SpreadsheetApp.openById(SPREADSHEET_ID);
      Logger.log("Using configured Spreadsheet ID: " + SPREADSHEET_ID);
    } catch (e) {
      Logger.log("Failed to open spreadsheet by ID: " + e.toString());
    }
  }
  
  if (!ss) {
    try {
      ss = SpreadsheetApp.getActiveSpreadsheet();
      Logger.log("Using active bound spreadsheet: " + ss.getName());
    } catch (e) {
      Logger.log("No active spreadsheet found. Creating a new one...");
      ss = SpreadsheetApp.create("NEXUS CRM — 2026–27");
      Logger.log("Created a new spreadsheet. ID: " + ss.getId());
      Logger.log("IMPORTANT: Please update SPREADSHEET_ID in Config.gs with this ID: " + ss.getId());
    }
  }
  
  if (!ss) {
    throw new Error("Could not initialize spreadsheet. Verify permissions or SPREADSHEET_ID in Config.gs.");
  }

  // Define schemas for all 22 tabs
  var schemas = {
    "00_Settings": ["settingKey", "settingValue", "description", "active"],
    "01_Users": ["userId", "firebaseUid", "name", "email", "phone", "role", "teamId", "position", "active", "joinDate", "profilePhotoUrl", "createdAt", "updatedAt"],
    "02_Teams": ["teamId", "teamName", "teamCode", "leadUserId", "description", "active", "createdAt", "updatedAt"],
    "03_Events": ["eventId", "eventName", "eventCategory", "eventDate", "startTime", "endTime", "venue", "leadTeamId", "supportingTeamIds", "eventStatus", "description", "createdBy", "createdAt", "updatedAt", "registrationStartDate", "registrationEndDate", "permissionDeadline", "creativeDeadline", "formDeadline", "promotionStartDate", "eventReportDeadline", "driveFolderUrl"],
    "04_Tasks": ["taskId", "eventId", "projectId", "taskTitle", "taskDescription", "teamId", "assignedTo", "assignedBy", "verifierId", "priority", "startDate", "deadline", "status", "completionPercent", "remarks", "rejectionRemarks", "completionDate", "driveLink", "isAutoGenerated", "sourceTemplateId", "createdAt", "updatedAt"],
    "05_Task_Updates": ["updateId", "taskId", "updatedBy", "previousStatus", "newStatus", "previousCompletion", "newCompletion", "remarks", "updatedAt"],
    "06_Creative": ["creativeId", "eventId", "creativeType", "title", "designerId", "contentOwnerId", "contentReceived", "designStarted", "reviewStatus", "approved", "published", "deadline", "postingDate", "assetUrl", "remarks", "createdAt", "updatedAt"],
    "07_Social_Media": ["contentId", "contentType", "eventId", "title", "platform", "responsiblePerson", "contentDeadline", "designDeadline", "approvalStatus", "postingDate", "status", "publishedUrl", "remarks", "createdAt", "updatedAt"],
    "08_Newsletter": ["newsletterId", "month", "year", "theme", "contentOwner", "designer", "deadline", "approvalStatus", "published", "publishedDate", "driveUrl", "remarks"],
    "09_Birthdays": ["birthdayId", "facultyName", "department", "birthday", "month", "posterAssigned", "contentAssigned", "designDeadline", "approvalStatus", "postingDate", "status", "remarks"],
    "10_Achievements": ["achievementId", "name", "department", "achievement", "category", "achievementDate", "proofUrl", "contentWriterId", "designerId", "approvalStatus", "postingDate", "instagramUrl", "createdAt", "updatedAt"],
    "11_Forms": ["formId", "formName", "eventId", "ownerId", "creationDeadline", "launchDate", "closingDate", "responseCount", "status", "formUrl", "responseSheetUrl", "createdAt", "updatedAt"],
    "12_Issues": ["issueId", "issueTitle", "eventId", "teamId", "severity", "dateRaised", "actionRequired", "ownerId", "deadline", "resolution", "status", "createdBy", "createdAt", "updatedAt"],
    "13_Meetings": ["meetingId", "meetingDate", "meetingType", "agenda", "decision", "responsiblePerson", "deadline", "status", "remarks", "createdBy", "createdAt"],
    "14_Budget": ["budgetId", "eventId", "category", "description", "estimatedBudget", "actualExpense", "amountPaid", "pendingAmount", "vendor", "sponsor", "invoiceUrl", "approvalStatus", "approvedBy", "createdAt", "updatedAt"],
    "15_Recognition": ["recognitionId", "userId", "recognitionType", "month", "year", "reason", "eventId", "volunteerHours", "approvedBy", "certificateUrl", "createdAt"],
    "16_Documents": ["documentId", "eventId", "documentType", "documentName", "driveUrl", "uploadedBy", "uploadedAt", "description"],
    "17_Reports": ["reportId", "reportType", "periodStart", "periodEnd", "generatedAt", "generatedBy", "summary", "reportUrl"],
    "18_Performance": ["performanceId", "userId", "period", "taskCompletionScore", "onTimeScore", "eventParticipationScore", "meetingAttendanceScore", "initiativeScore", "teamCoordinationScore", "responsibilityScore", "communicationScore", "qualityScore", "consistencyScore", "overallScore", "remarks", "evaluatedBy", "evaluatedAt"],
    "19_Audit_Log": ["auditId", "timestamp", "userId", "action", "entityType", "entityId", "previousValue", "newValue", "ipOrSessionReference", "result"],
    "20_Event_Templates": ["templateId", "templateName", "taskTitle", "taskDescription", "dayOffset", "teamId", "defaultPriority", "required", "active"],
    "21_Dashboard_Data": ["metricKey", "metricValue", "calculatedAt"],
    "22_Notifications": ["notificationId", "eventType", "taskId", "eventId", "recipientUserId", "recipientEmail", "subject", "status", "sentAt", "errorMessage", "createdAt"]
  };

  var tabOrder = [
    "00_Settings", "01_Users", "02_Teams", "03_Events", "04_Tasks", "05_Task_Updates",
    "06_Creative", "07_Social_Media", "08_Newsletter", "09_Birthdays", "10_Achievements",
    "11_Forms", "12_Issues", "13_Meetings", "14_Budget", "15_Recognition", "16_Documents",
    "17_Reports", "18_Performance", "19_Audit_Log", "20_Event_Templates", "21_Dashboard_Data",
    "22_Notifications"
  ];

  // 2. Idempotent sheet creation
  for (var index = 0; index < tabOrder.length; index++) {
    var sheetName = tabOrder[index];
    var columns = schemas[sheetName];
    var sheet = ss.getSheetByName(sheetName);
    
    if (!sheet) {
      sheet = ss.insertSheet(sheetName);
      Logger.log("Created sheet: " + sheetName);
    } else {
      Logger.log("Sheet already exists, enforcing schema: " + sheetName);
    }
    
    // Set sheet order/index
    sheet.activate();
    ss.moveActiveSheet(index + 1);
    
    // Set headers
    sheet.getRange(1, 1, 1, columns.length).setValues([columns]);
    sheet.getRange(1, 1, 1, columns.length).setFontWeight("bold");
    sheet.setHiddenGridlines(false);
    
    // Freeze header
    sheet.setFrozenRows(1);
    
    // Create filter on headers (if none exists)
    var filter = sheet.getFilter();
    if (!filter) {
      sheet.getRange(1, 1, sheet.getMaxRows(), columns.length).createFilter();
    }
    
    // Set column date formatting programmatically
    applyNumberFormats(sheet, columns);
    
    // Protect header range idempotently
    var rangeProtections = sheet.getProtections(SpreadsheetApp.ProtectionType.RANGE);
    var headerProtected = false;
    for (var p = 0; p < rangeProtections.length; p++) {
      if (rangeProtections[p].getDescription() === "Header Protection") {
        headerProtected = true;
        break;
      }
    }
    if (!headerProtected) {
      var headerRange = sheet.getRange(1, 1, 1, columns.length);
      var headerProtection = headerRange.protect().setDescription("Header Protection");
      var me = Session.getEffectiveUser();
      headerProtection.addEditor(me);
      headerProtection.removeEditors(headerProtection.getEditors());
      if (headerProtection.canDomainEdit()) {
        headerProtection.setDomainEdit(false);
      }
    }
  }

  // 3. Remove default "Sheet1" if present
  var defaultSheet = ss.getSheetByName("Sheet1");
  if (defaultSheet) {
    try {
      ss.deleteSheet(defaultSheet);
      Logger.log("Deleted default Sheet1.");
    } catch (e) {
      Logger.log("Could not delete default Sheet1: " + e.toString());
    }
  }

  // 4. Seeding static configuration sheets
  seedSettings(ss);
  seedTeams(ss);
  seedTemplates(ss);

  // 5. Apply dropdown validations
  applyAllDropdownValidations(ss);

  // 6. Apply status conditional formatting
  var tasksSheet = ss.getSheetByName("04_Tasks");
  if (tasksSheet) {
    applyStatusConditionalFormatting(tasksSheet, 12); // column 12 = status
  }
  
  var creativeSheet = ss.getSheetByName("06_Creative");
  if (creativeSheet) {
    applyCreativeStatusFormatting(creativeSheet, 9); // column 9 = reviewStatus
  }

  // 7. Protect Administrative Sheets (00_Settings, 01_Users, 18_Performance, 19_Audit_Log, 21_Dashboard_Data)
  var protectedSheets = ["00_Settings", "01_Users", "18_Performance", "19_Audit_Log", "21_Dashboard_Data"];
  for (var s = 0; s < protectedSheets.length; s++) {
    var pSheet = ss.getSheetByName(protectedSheets[s]);
    if (pSheet) {
      var sheetProtections = pSheet.getProtections(SpreadsheetApp.ProtectionType.SHEET);
      var isSheetProtected = false;
      for (var sp = 0; sp < sheetProtections.length; sp++) {
        isSheetProtected = true;
        break;
      }
      if (!isSheetProtected) {
        var sheetProtection = pSheet.protect().setDescription("System protected sheet");
        var me = Session.getEffectiveUser();
        sheetProtection.addEditor(me);
        sheetProtection.removeEditors(sheetProtection.getEditors());
        if (sheetProtection.canDomainEdit()) {
          sheetProtection.setDomainEdit(false);
        }
        Logger.log("Protected sheet: " + protectedSheets[s]);
      }
    }
  }

  Logger.log("setupNexusSpreadsheet completed successfully.");
}

/**
 * Formats cells based on column names.
 */
function applyNumberFormats(sheet, columns) {
  for (var c = 0; c < columns.length; c++) {
    var colName = columns[c];
    var colLower = colName.toLowerCase();
    var columnIndex = c + 1;
    var range = sheet.getRange(2, columnIndex, sheet.getMaxRows() - 1, 1);
    
    if (colLower.endsWith("date") || colLower.endsWith("deadline") || colLower === "birthday") {
      range.setNumberFormat("dd/MM/yyyy");
    } else if (colLower.endsWith("at") || colLower === "timestamp") {
      range.setNumberFormat("dd/MM/yyyy HH:mm:ss");
    }
  }
}

/**
 * Seeds Settings sheet.
 */
function seedSettings(ss) {
  var sheet = ss.getSheetByName("00_Settings");
  if (!sheet) return;

  var seedData = [
    ["TASK_STATUS_COMPLETED", "COMPLETED", "Status representing completed tasks", "TRUE"],
    ["TASK_STATUS_IN_PROGRESS", "IN_PROGRESS", "Status representing tasks currently in progress", "TRUE"],
    ["TASK_STATUS_NOT_STARTED", "NOT_STARTED", "Status representing tasks not started yet", "TRUE"],
    ["TASK_STATUS_DELAYED", "DELAYED", "Status representing overdue tasks or delayed tasks", "TRUE"],
    ["TASK_STATUS_BLOCKED", "BLOCKED", "Status representing tasks blocked by external factors", "TRUE"],
    ["PRIORITY_LOW", "LOW", "Low priority task", "TRUE"],
    ["PRIORITY_MEDIUM", "MEDIUM", "Medium priority task", "TRUE"],
    ["PRIORITY_HIGH", "HIGH", "High priority task", "TRUE"],
    ["PRIORITY_CRITICAL", "CRITICAL", "Critical priority task", "TRUE"],
    ["WORKLOAD_NORMAL_MAX", "5", "Maximum active tasks for NORMAL workload status", "TRUE"],
    ["WORKLOAD_HIGH_MAX", "10", "Maximum active tasks for HIGH workload status", "TRUE"],
    ["DEFAULT_TIMEZONE", "Asia/Kolkata", "Default system timezone", "TRUE"],
    ["ACADEMIC_SESSION", "2026-27", "Current academic session", "TRUE"],
    ["ORGANIZATION_NAME", "NEXUS Forum", "Name of the organization", "TRUE"],
    ["PERFORMANCE_WEIGHT_TASK_COMPLETION", "0.15", "Performance weight for Task Completion Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_ON_TIME", "0.15", "Performance weight for On-Time Delivery Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_EVENT_PARTICIPATION", "0.10", "Performance weight for Event Participation Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_MEETING_ATTENDANCE", "0.10", "Performance weight for Meeting Attendance Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_INITIATIVE", "0.10", "Performance weight for Initiative Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_TEAM_COORDINATION", "0.10", "Performance weight for Team Coordination Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_RESPONSIBILITY", "0.10", "Performance weight for Responsibility Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_COMMUNICATION", "0.10", "Performance weight for Communication Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_QUALITY", "0.05", "Performance weight for Quality of Work Score", "TRUE"],
    ["PERFORMANCE_WEIGHT_CONSISTENCY", "0.05", "Performance weight for Consistency Score", "TRUE"]
  ];

  var existingKeys = {};
  if (sheet.getLastRow() > 1) {
    var data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 1).getValues();
    for (var i = 0; i < data.length; i++) {
      existingKeys[data[i][0]] = true;
    }
  }

  var rowsToInsert = [];
  for (var i = 0; i < seedData.length; i++) {
    if (!existingKeys[seedData[i][0]]) {
      rowsToInsert.push(seedData[i]);
    }
  }

  if (rowsToInsert.length > 0) {
    sheet.getRange(sheet.getLastRow() + 1, 1, rowsToInsert.length, 4).setValues(rowsToInsert);
    Logger.log("Seeded " + rowsToInsert.length + " settings.");
  }
}

/**
 * Seeds Teams sheet.
 */
function seedTeams(ss) {
  var sheet = ss.getSheetByName("02_Teams");
  if (!sheet) return;

  var timestamp = new Date();
  var seedData = [
    ["TEAM-001", "Technical", "TECH", "", "Websites, apps, coding, systems, servers", "TRUE", timestamp, timestamp],
    ["TEAM-002", "Design", "DSGN", "", "Creatives, UI, posters, branding, merch", "TRUE", timestamp, timestamp],
    ["TEAM-003", "Content", "CONT", "", "Scripts, writing, blogs, documentation", "TRUE", timestamp, timestamp],
    ["TEAM-004", "Social Media", "SMED", "", "Instagram, LinkedIn, promotions, campaigns", "TRUE", timestamp, timestamp],
    ["TEAM-005", "Photography & Videography", "PVID", "", "Photos, reels, event shoots, editing", "TRUE", timestamp, timestamp],
    ["TEAM-006", "Cultural", "CULT", "", "Performances, anchors, drama, choreography", "TRUE", timestamp, timestamp],
    ["TEAM-007", "Sports", "SPRT", "", "Athletics, indoor sports, tournament coordination", "TRUE", timestamp, timestamp],
    ["TEAM-008", "Discipline", "DISC", "", "Security, crowd management, venue coordination", "TRUE", timestamp, timestamp]
  ];

  var existingIds = {};
  if (sheet.getLastRow() > 1) {
    var data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 1).getValues();
    for (var i = 0; i < data.length; i++) {
      existingIds[data[i][0]] = true;
    }
  }

  var rowsToInsert = [];
  for (var i = 0; i < seedData.length; i++) {
    if (!existingIds[seedData[i][0]]) {
      rowsToInsert.push(seedData[i]);
    }
  }

  if (rowsToInsert.length > 0) {
    sheet.getRange(sheet.getLastRow() + 1, 1, rowsToInsert.length, 8).setValues(rowsToInsert);
    Logger.log("Seeded " + rowsToInsert.length + " teams.");
  }
}

/**
 * Seeds Event Templates.
 */
function seedTemplates(ss) {
  var sheet = ss.getSheetByName("20_Event_Templates");
  if (!sheet) return;

  var seedData = [
    ["TPL-001", "Technical Event", "Event Finalization", "Draft complete event design sheet, agenda and outline.", "-30", "TEAM-001", "HIGH", "TRUE", "TRUE"],
    ["TPL-002", "Technical Event", "Venue / Permission", "Draft and submit official permission letter to administration.", "-25", "TEAM-001", "HIGH", "TRUE", "TRUE"],
    ["TPL-003", "Technical Event", "Design Brief", "Submit creative request to design team for poster and stories.", "-20", "TEAM-002", "MEDIUM", "TRUE", "TRUE"],
    ["TPL-004", "Technical Event", "Promotion Launch", "Initiate social media promotions and countdown stories.", "-15", "TEAM-004", "MEDIUM", "TRUE", "TRUE"],
    ["TPL-005", "Technical Event", "Registration Google Form", "Create registration form and map to database sheets.", "-10", "TEAM-001", "HIGH", "TRUE", "TRUE"],
    ["TPL-006", "Technical Event", "Event Report Submission", "Compile final event report, budget spreadsheet and submit to President.", "5", "TEAM-001", "MEDIUM", "TRUE", "TRUE"]
  ];

  var existingKeys = {};
  if (sheet.getLastRow() > 1) {
    var data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 3).getValues(); // templateId, templateName, taskTitle
    for (var i = 0; i < data.length; i++) {
      var key = data[i][0] + "_" + data[i][2];
      existingKeys[key] = true;
    }
  }

  var rowsToInsert = [];
  for (var i = 0; i < seedData.length; i++) {
    var key = seedData[i][0] + "_" + seedData[i][2];
    if (!existingKeys[key]) {
      rowsToInsert.push(seedData[i]);
    }
  }

  if (rowsToInsert.length > 0) {
    sheet.getRange(sheet.getLastRow() + 1, 1, rowsToInsert.length, 9).setValues(rowsToInsert);
    Logger.log("Seeded " + rowsToInsert.length + " templates.");
  }
}

/**
 * Apply cell list dropdown validations.
 */
function applyAllDropdownValidations(ss) {
  var dropdownConfigs = [
    { sheet: "01_Users", col: 6, list: ["PRESIDENT", "VP", "LEAD", "MEMBER", "GENERAL_MEMBER"] },
    { sheet: "01_Users", col: 9, list: ["TRUE", "FALSE"] },
    
    { sheet: "02_Teams", col: 6, list: ["TRUE", "FALSE"] },
    
    { sheet: "03_Events", col: 10, list: ["PLANNING", "UPCOMING", "ONGOING", "COMPLETED", "CANCELLED", "POSTPONED"] },
    
    { sheet: "04_Tasks", col: 9, list: ["LOW", "MEDIUM", "HIGH", "CRITICAL"] },
    { sheet: "04_Tasks", col: 12, list: ["NOT_STARTED", "IN_PROGRESS", "COMPLETED", "DELAYED", "BLOCKED", "CANCELLED"] },
    { sheet: "04_Tasks", col: 17, list: ["TRUE", "FALSE"] },
    
    { sheet: "06_Creative", col: 9, list: ["BRIEF", "CONTENT_RECEIVED", "DESIGN_STARTED", "REVIEW", "APPROVED", "PUBLISHED"] },
    { sheet: "06_Creative", col: 10, list: ["TRUE", "FALSE"] },
    { sheet: "06_Creative", col: 11, list: ["TRUE", "FALSE"] },
    
    { sheet: "07_Social_Media", col: 2, list: ["POST", "REEL", "STORY", "EVENT_PROMOTION", "COUNTDOWN", "BIRTHDAY", "ACHIEVEMENT", "FACULTY_FEATURE", "STUDENT_SPOTLIGHT", "NEWSLETTER", "EVENT_RECAP"] },
    { sheet: "07_Social_Media", col: 9, list: ["PENDING", "APPROVED", "REJECTED"] },
    { sheet: "07_Social_Media", col: 11, list: ["PLANNING", "DRAFT", "REVIEW", "SCHEDULED", "PUBLISHED"] },
    
    { sheet: "08_Newsletter", col: 8, list: ["PENDING", "APPROVED", "REJECTED"] },
    { sheet: "08_Newsletter", col: 9, list: ["TRUE", "FALSE"] },
    
    { sheet: "09_Birthdays", col: 9, list: ["PENDING", "APPROVED", "REJECTED"] },
    { sheet: "09_Birthdays", col: 11, list: ["PLANNING", "DESIGNED", "PUBLISHED", "SKIPPED"] },
    
    { sheet: "10_Achievements", col: 10, list: ["PENDING", "APPROVED", "REJECTED"] },
    
    { sheet: "11_Forms", col: 9, list: ["PLANNING", "CREATING", "ACTIVE", "CLOSED", "ARCHIVED"] },
    
    { sheet: "12_Issues", col: 5, list: ["LOW", "MEDIUM", "HIGH", "CRITICAL"] },
    { sheet: "12_Issues", col: 11, list: ["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"] },
    
    { sheet: "13_Meetings", col: 8, list: ["SCHEDULED", "COMPLETED", "CANCELLED"] },
    
    { sheet: "14_Budget", col: 12, list: ["PENDING", "APPROVED", "REJECTED"] },
    
    { sheet: "15_Recognition", col: 3, list: ["MEMBER_OF_MONTH", "BEST_VOLUNTEER", "BEST_TEAM", "OUTSTANDING_CONTRIBUTION"] },
    
    { sheet: "17_Reports", col: 2, list: ["WEEKLY", "MONTHLY", "EVENT", "SEMESTER", "ANNUAL"] },
    
    { sheet: "20_Event_Templates", col: 7, list: ["LOW", "MEDIUM", "HIGH", "CRITICAL"] },
    { sheet: "20_Event_Templates", col: 8, list: ["TRUE", "FALSE"] },
    { sheet: "20_Event_Templates", col: 9, list: ["TRUE", "FALSE"] }
  ];

  for (var i = 0; i < dropdownConfigs.length; i++) {
    var conf = dropdownConfigs[i];
    var sheet = ss.getSheetByName(conf.sheet);
    if (sheet) {
      var range = sheet.getRange(2, conf.col, sheet.getMaxRows() - 1, 1);
      var rule = SpreadsheetApp.newDataValidation()
        .requireValueInList(conf.list, true)
        .setAllowInvalid(false)
        .setHelpText("Value must be one of: " + conf.list.join(", "))
        .build();
      range.setDataValidation(rule);
    }
  }
  Logger.log("Applied cell validations across sheets.");
}

/**
 * Apply task status conditional formatting.
 */
function applyStatusConditionalFormatting(sheet, colIndex) {
  var range = sheet.getRange(2, colIndex, sheet.getMaxRows() - 1, 1);
  var rules = [];

  // Rule 1: COMPLETED -> light green background, dark green text
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("COMPLETED")
    .setBackground("#e2f0d9")
    .setFontColor("#385723")
    .setRanges([range])
    .build());

  // Rule 2: IN_PROGRESS -> light yellow background, dark yellow text
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("IN_PROGRESS")
    .setBackground("#fff2cc")
    .setFontColor("#7f6000")
    .setRanges([range])
    .build());

  // Rule 3: NOT_STARTED -> light blue background, dark blue text
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("NOT_STARTED")
    .setBackground("#ddebf7")
    .setFontColor("#1f4e78")
    .setRanges([range])
    .build());

  // Rule 4: DELAYED -> light red background, dark red text
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("DELAYED")
    .setBackground("#fce4d6")
    .setFontColor("#c00000")
    .setRanges([range])
    .build());

  // Rule 5: BLOCKED -> dark red background, white text
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("BLOCKED")
    .setBackground("#800000")
    .setFontColor("#ffffff")
    .setRanges([range])
    .build());

  sheet.setConditionalFormatRules(rules);
  Logger.log("Applied task status conditional formatting rules.");
}

/**
 * Apply creative status conditional formatting.
 */
function applyCreativeStatusFormatting(sheet, colIndex) {
  var range = sheet.getRange(2, colIndex, sheet.getMaxRows() - 1, 1);
  var rules = [];

  // APPROVED / PUBLISHED -> light green
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("APPROVED")
    .setBackground("#e2f0d9")
    .setFontColor("#385723")
    .setRanges([range])
    .build());

  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("PUBLISHED")
    .setBackground("#e2f0d9")
    .setFontColor("#385723")
    .setRanges([range])
    .build());

  // BRIEF / REVIEW -> light yellow
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("REVIEW")
    .setBackground("#fff2cc")
    .setFontColor("#7f6000")
    .setRanges([range])
    .build());

  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("BRIEF")
    .setBackground("#fff2cc")
    .setFontColor("#7f6000")
    .setRanges([range])
    .build());

  // DESIGN_STARTED / CONTENT_RECEIVED -> light blue
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("DESIGN_STARTED")
    .setBackground("#ddebf7")
    .setFontColor("#1f4e78")
    .setRanges([range])
    .build());

  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenTextEqualTo("CONTENT_RECEIVED")
    .setBackground("#ddebf7")
    .setFontColor("#1f4e78")
    .setRanges([range])
    .build());

  sheet.setConditionalFormatRules(rules);
  Logger.log("Applied creative status conditional formatting rules.");
}
