// TasksHandler.gs — Core handlers for Tasks management (04_Tasks sheet).

/**
 * Returns all active (non-cancelled) tasks.
 * @returns {Array<Object>} List of active tasks
 */
function handleListTasks() {
  var repo = new SheetRepository("04_Tasks", "TSK", "taskId");
  return repo.getAll();
}

/**
 * Retrieves details for a single task by ID.
 * @param {string} taskId - Unique ID of the task
 * @returns {Object} The task details
 */
function handleGetTask(taskId) {
  if (!taskId) {
    throw new Error("Missing task ID.");
  }
  var repo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = repo.getById(taskId);
  if (!task) {
    throw new Error("Task not found with ID: " + taskId);
  }
  return task;
}

/**
 * Creates a new task. Enforces that new tasks start as NOT_STARTED / 0%.
 * @param {Object} taskData - Task parameter payload
 * @param {string} creatorUserId - User ID of the creator
 * @returns {Object} The newly created task record
 */
function handleCreateTask(taskData, creatorUserId) {
  if (!taskData || !taskData.taskTitle) {
    throw new Error("Invalid payload: taskTitle is required.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");

  var newTask = {
    eventId: taskData.eventId || "",
    projectId: taskData.projectId || "",
    taskTitle: taskData.taskTitle,
    taskDescription: taskData.taskDescription || "",
    teamId: taskData.teamId || "",
    assignedTo: taskData.assignedTo || "",
    assignedBy: creatorUserId || "",
    verifierId: taskData.verifierId || creatorUserId || "",
    priority: taskData.priority || "MEDIUM",
    startDate: taskData.startDate ? new Date(taskData.startDate) : new Date(),
    deadline: taskData.deadline ? new Date(taskData.deadline) : "",
    status: "NOT_STARTED", // Enforce initial status rules
    completionPercent: 0,   // Enforce initial progress rules
    remarks: taskData.remarks || "",
    rejectionRemarks: "",
    completionDate: "",
    driveLink: taskData.driveLink || "",
    isAutoGenerated: String(taskData.isAutoGenerated).toUpperCase() === "TRUE" ? "TRUE" : "FALSE",
    sourceTemplateId: taskData.sourceTemplateId || ""
  };

  var insertedTask = tasksRepo.insert(newTask);
  
  // Send email notification to assignee
  if (insertedTask.assignedTo) {
    sendNotification("TASK_ASSIGNED", insertedTask, insertedTask.assignedTo);
  }
  
  // Log task updates history entry
  logTaskUpdate(
    insertedTask.taskId,
    creatorUserId || "SYSTEM",
    "",
    "NOT_STARTED",
    "",
    0,
    taskData.remarks || "Task created."
  );

  return insertedTask;
}

/**
 * Updates a task. Enforces status consistency, history updates, and audit logging.
 * @param {string} taskId - Unique ID of the task to update
 * @param {Object} taskData - Fields to update
 * @param {string} operatorUserId - User ID of the updating operator
 * @returns {Object} The updated task record
 */
function handleUpdateTask(taskId, taskData, operatorUserId) {
  if (!taskId || !taskData) {
    throw new Error("Missing task ID or update payload.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var existingTask = tasksRepo.getById(taskId);
  if (!existingTask) {
    throw new Error("Task not found with ID: " + taskId);
  }

  var updateFields = {};
  if (taskData.hasOwnProperty("taskTitle")) updateFields.taskTitle = taskData.taskTitle;
  if (taskData.hasOwnProperty("taskDescription")) updateFields.taskDescription = taskData.taskDescription;
  if (taskData.hasOwnProperty("teamId")) updateFields.teamId = taskData.teamId;
  if (taskData.hasOwnProperty("priority")) updateFields.priority = taskData.priority;
  if (taskData.hasOwnProperty("driveLink")) updateFields.driveLink = taskData.driveLink;
  if (taskData.hasOwnProperty("verifierId")) updateFields.verifierId = taskData.verifierId;
  if (taskData.hasOwnProperty("remarks")) updateFields.remarks = taskData.remarks;
  if (taskData.hasOwnProperty("rejectionRemarks")) updateFields.rejectionRemarks = taskData.rejectionRemarks;

  // 1. Enforce Status and Progress consistency rules
  var targetStatus = taskData.status ? taskData.status.toUpperCase() : existingTask.status;
  var targetPercent = taskData.completionPercent !== undefined ? Number(taskData.completionPercent) : Number(existingTask.completionPercent);

  // Status mapping adjustments
  if (taskData.hasOwnProperty("status") && !taskData.hasOwnProperty("completionPercent")) {
    if (targetStatus === "COMPLETED" || targetStatus === "VERIFY") {
      targetPercent = 100;
    } else if (targetStatus === "NOT_STARTED") {
      targetPercent = 0;
    }
  } else if (!taskData.hasOwnProperty("status") && taskData.hasOwnProperty("completionPercent")) {
    if (targetPercent === 100) {
      if (existingTask.status !== "VERIFY" && existingTask.status !== "COMPLETED") {
        targetStatus = "COMPLETED";
      }
    } else if (existingTask.status === "COMPLETED" && targetPercent < 100) {
      targetStatus = targetPercent === 0 ? "NOT_STARTED" : "IN_PROGRESS";
    }
  }

  updateFields.status = targetStatus;
  updateFields.completionPercent = targetPercent;

  // Manage completionDate
  if (targetStatus === "COMPLETED") {
    updateFields.completionDate = existingTask.completionDate ? existingTask.completionDate : new Date();
  } else if (targetStatus !== "VERIFY") {
    updateFields.completionDate = "";
  }

  // 2. Deadline Changes (Enforce security logs)
  if (taskData.hasOwnProperty("deadline")) {
    var newDeadline = taskData.deadline ? new Date(taskData.deadline) : "";
    var oldDeadlineStr = existingTask.deadline ? String(new Date(existingTask.deadline)) : "";
    var newDeadlineStr = newDeadline ? String(newDeadline) : "";
    
    if (oldDeadlineStr !== newDeadlineStr) {
      updateFields.deadline = newDeadline;
      logAudit(
        operatorUserId,
        "tasks.updateDeadline",
        "Tasks",
        taskId,
        oldDeadlineStr,
        newDeadlineStr,
        "SUCCESS"
      );
    }
  }

  // 3. Task Reassignment (Enforce security logs & notification)
  var isReassigned = false;
  if (taskData.hasOwnProperty("assignedTo") && taskData.assignedTo !== existingTask.assignedTo) {
    updateFields.assignedTo = taskData.assignedTo;
    isReassigned = true;
    logAudit(
      operatorUserId,
      "tasks.assign",
      "Tasks",
      taskId,
      existingTask.assignedTo || "UNASSIGNED",
      taskData.assignedTo || "UNASSIGNED",
      "SUCCESS"
    );
  }

  // 4. Task History Updates Log
  var statusChanged = targetStatus !== existingTask.status;
  var percentChanged = targetPercent !== Number(existingTask.completionPercent);
  
  if (statusChanged || percentChanged || isReassigned) {
    logTaskUpdate(
      taskId,
      operatorUserId,
      existingTask.status,
      targetStatus,
      existingTask.completionPercent,
      targetPercent,
      taskData.remarks || "Task details updated."
    );
  }

  // Perform sheet update
  var updated = tasksRepo.update(taskId, updateFields);

  // 5. Trigger notifications based on detected state transitions
  if (isReassigned && updated.assignedTo) {
    sendNotification("TASK_REASSIGNED", updated, updated.assignedTo);
  } else if (statusChanged) {
    if (targetStatus === "BLOCKED") {
      sendNotification("TASK_BLOCKED", updated, updated.assignedBy || updated.verifierId, {
        blockReason: taskData.remarks || "Marked as blocked by team member."
      });
    } else if (targetStatus === "VERIFY") {
      sendNotification("TASK_READY_FOR_VERIFICATION", updated, updated.verifierId || updated.assignedBy, {
        remarks: taskData.remarks || ""
      });
    } else if (targetStatus === "COMPLETED" && existingTask.status === "VERIFY") {
      sendNotification("TASK_VERIFIED", updated, updated.assignedTo);
    } else if (targetStatus === "REJECTED") {
      sendNotification("TASK_REJECTED", updated, updated.assignedTo, {
        rejectionRemark: taskData.rejectionRemarks || taskData.remarks || ""
      });
    }
  }

  return updated;
}

/**
 * Task owner submits task for verification by leadership.
 * @param {string} taskId
 * @param {string} verifierId - Optional user ID of the chosen verifier
 * @param {string} remarks - Note from the submitter
 * @param {string} operatorUserId - Submitting user
 */
function handleTaskSubmitForVerification(taskId, verifierId, remarks, operatorUserId) {
  if (!taskId) throw new Error("Missing task ID.");

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = tasksRepo.getById(taskId);
  if (!task) throw new Error("Task not found with ID: " + taskId);

  var payload = {
    status: "VERIFY",
    completionPercent: 100,
    remarks: remarks || "Submitted for verification."
  };
  if (verifierId) {
    payload.verifierId = verifierId;
  }

  return handleUpdateTask(taskId, payload, operatorUserId);
}

/**
 * Verifier approves and verifies the task (marks as COMPLETED / VERIFIED).
 * @param {string} taskId
 * @param {string} remarks - Approval remarks
 * @param {string} operatorUserId - Approving verifier
 */
function handleTaskVerify(taskId, remarks, operatorUserId) {
  if (!taskId) throw new Error("Missing task ID.");

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = tasksRepo.getById(taskId);
  if (!task) throw new Error("Task not found with ID: " + taskId);

  var verifierUser = resolveNotificationRecipient(operatorUserId);
  var verifierName = verifierUser ? verifierUser.name : "Verifier";

  var updated = handleUpdateTask(taskId, {
    status: "COMPLETED",
    completionPercent: 100,
    remarks: remarks || "Task verified and approved by " + verifierName
  }, operatorUserId);

  logAudit(
    operatorUserId,
    "tasks.verify",
    "Tasks",
    taskId,
    task.status,
    "COMPLETED",
    "SUCCESS"
  );

  return updated;
}

/**
 * Verifier rejects the task and requests changes.
 * @param {string} taskId
 * @param {string} remarks - Mandatory feedback / rejection reason
 * @param {string} operatorUserId - Rejecting verifier
 */
function handleTaskReject(taskId, remarks, operatorUserId) {
  if (!taskId) throw new Error("Missing task ID.");
  if (!remarks) throw new Error("Rejection remarks / feedback reason is required.");

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = tasksRepo.getById(taskId);
  if (!task) throw new Error("Task not found with ID: " + taskId);

  var verifierUser = resolveNotificationRecipient(operatorUserId);
  var verifierName = verifierUser ? verifierUser.name : "Verifier";

  var updated = handleUpdateTask(taskId, {
    status: "REJECTED",
    rejectionRemarks: remarks,
    remarks: "Changes requested by " + verifierName + ": " + remarks
  }, operatorUserId);

  logAudit(
    operatorUserId,
    "tasks.reject",
    "Tasks",
    taskId,
    task.status,
    "REJECTED",
    "SUCCESS"
  );

  return updated;
}

/**
 * Updates a task's status directly.
 */
function handleUpdateTaskStatus(taskId, status, remarks, operatorUserId) {
  if (!status) {
    throw new Error("Status is required.");
  }
  var stat = status.toUpperCase();
  var proposedPercent = undefined;
  if (stat === "COMPLETED" || stat === "VERIFY") proposedPercent = 100;
  if (stat === "NOT_STARTED") proposedPercent = 0;

  return handleUpdateTask(taskId, {
    status: stat,
    completionPercent: proposedPercent,
    remarks: remarks
  }, operatorUserId);
}

/**
 * Updates a task's completion percent directly.
 */
function handleUpdateTaskProgress(taskId, completionPercent, remarks, operatorUserId) {
  if (completionPercent === undefined || isNaN(Number(completionPercent))) {
    throw new Error("Valid completionPercent is required.");
  }
  var percent = Number(completionPercent);
  var proposedStatus = undefined;
  if (percent === 100) {
    proposedStatus = "COMPLETED";
  } else if (percent === 0) {
    proposedStatus = "NOT_STARTED";
  }

  return handleUpdateTask(taskId, {
    status: proposedStatus,
    completionPercent: percent,
    remarks: remarks
  }, operatorUserId);
}

/**
 * Calculates the target user's workload indicators.
 * @param {string} targetUserId - Unique ID of the target user
 * @returns {Object} Workload information
 */
function handleGetUserWorkload(targetUserId) {
  if (!targetUserId) {
    throw new Error("Missing target user ID.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var userTasks = tasksRepo.find({ assignedTo: targetUserId });
  
  var activeCount = 0;
  for (var i = 0; i < userTasks.length; i++) {
    var status = userTasks[i].status ? userTasks[i].status.toUpperCase() : "";
    // Active tasks = NOT_STARTED, IN_PROGRESS, DELAYED, BLOCKED, VERIFY, REJECTED
    if (["NOT_STARTED", "IN_PROGRESS", "DELAYED", "BLOCKED", "VERIFY", "REJECTED"].indexOf(status) !== -1) {
      activeCount++;
    }
  }

  var settingsRepo = new SheetRepository("00_Settings", null, "settingKey");
  var normalMaxVal = settingsRepo.getById("WORKLOAD_NORMAL_MAX");
  var highMaxVal = settingsRepo.getById("WORKLOAD_HIGH_MAX");
  
  var normalMax = normalMaxVal ? parseInt(normalMaxVal.settingValue, 10) : 5;
  var highMax = highMaxVal ? parseInt(highMaxVal.settingValue, 10) : 10;

  var workloadState = "NORMAL";
  if (activeCount > normalMax && activeCount <= highMax) {
    workloadState = "HIGH";
  } else if (activeCount > highMax) {
    workloadState = "OVERLOADED";
  }

  return {
    activeCount: activeCount,
    workloadState: workloadState
  };
}

/**
 * Internal helper to write update entries to the 05_Task_Updates sheet.
 */
function logTaskUpdate(taskId, operatorUserId, previousStatus, newStatus, previousCompletion, newCompletion, remarks) {
  try {
    var updatesRepo = new SheetRepository("05_Task_Updates", "UPD", "updateId");
    updatesRepo.insert({
      taskId: taskId,
      updatedBy: operatorUserId || "SYSTEM",
      previousStatus: previousStatus || "",
      newStatus: newStatus || "",
      previousCompletion: previousCompletion !== "" ? Number(previousCompletion) : "",
      newCompletion: newCompletion !== "" ? Number(newCompletion) : "",
      remarks: remarks || ""
    });
  } catch (err) {
    Logger.log("Failed to write task update log: " + err.toString());
  }
}
