// TasksHandler.gs — Core handlers for Tasks management (04_Tasks sheet).

/**
 * Returns all active (non-cancelled) tasks, excluding tasks belonging to cancelled/deleted events.
 * @returns {Array<Object>} List of active tasks
 */
function handleListTasks() {
  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var eventsRepo = new SheetRepository("03_Events", "EVT", "eventId");

  var activeEvents = eventsRepo.getAll();
  var activeEventMap = {};
  for (var e = 0; e < activeEvents.length; e++) {
    activeEventMap[activeEvents[e].eventId] = true;
  }

  var allTasks = tasksRepo.getAll();
  return allTasks.filter(function(task) {
    if (task.eventId && !activeEventMap[task.eventId]) {
      // Event was cancelled or deleted, exclude this task
      return false;
    }
    return true;
  });
}

/**
 * Retrieves details for a single task by ID.
 * @param {string} taskId - Unique ID of the task
 * @returns {Object} The task details
 */
function handleGetTask(taskId) {
  if (!taskId) {
    throw new Error("Missing task ID.");
  }
  var repo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = repo.getById(taskId);
  if (!task) {
    throw new Error("Task not found with ID: " + taskId);
  }
  return task;
}

/**
 * Creates a new task. Supports multi-department assignment and individual sub-progress tracking.
 * @param {Object} taskData - Task parameter payload
 * @param {string} creatorUserId - User ID of the creator
 * @returns {Object} The newly created task record
 */
function handleCreateTask(taskData, creatorUserId) {
  if (!taskData || !taskData.taskTitle) {
    throw new Error("Invalid payload: taskTitle is required.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");

  // Format department assignments
  var deptAssignments = [];
  if (taskData.departmentAssignments) {
    if (typeof taskData.departmentAssignments === "string") {
      try {
        deptAssignments = JSON.parse(taskData.departmentAssignments);
      } catch (e) {
        deptAssignments = [];
      }
    } else if (Array.isArray(taskData.departmentAssignments)) {
      deptAssignments = taskData.departmentAssignments;
    }
  }

  // Ensure default sub-assignment values
  if (deptAssignments.length > 0) {
    deptAssignments = deptAssignments.map(function(item) {
      return {
        teamId: item.teamId || "",
        teamName: item.teamName || "",
        assignedTo: item.assignedTo || "",
        assigneeName: item.assigneeName || "",
        status: item.status || "NOT_STARTED",
        progress: Number(item.progress) || 0,
        remarks: item.remarks || "",
        lastUpdated: new Date().toISOString()
      };
    });
  }

  // Resolve primary team and assignee from sub-assignments if omitted
  var primaryTeam = taskData.teamId || (deptAssignments.length > 0 ? deptAssignments[0].teamId : "");
  var primaryAssignee = taskData.assignedTo || (deptAssignments.length > 0 ? deptAssignments[0].assignedTo : "");

  // Calculate initial aggregate progress
  var initialPercent = 0;
  if (deptAssignments.length > 0) {
    var totalSubProgress = deptAssignments.reduce(function(acc, curr) { return acc + (Number(curr.progress) || 0); }, 0);
    initialPercent = Math.round(totalSubProgress / deptAssignments.length);
  }

  var newTask = {
    eventId: taskData.eventId || "",
    projectId: taskData.projectId || "",
    taskTitle: taskData.taskTitle,
    taskDescription: taskData.taskDescription || "",
    teamId: primaryTeam,
    assignedTo: primaryAssignee,
    assignedBy: creatorUserId || "",
    verifierId: taskData.verifierId || creatorUserId || "",
    priority: taskData.priority || "MEDIUM",
    startDate: taskData.startDate ? new Date(taskData.startDate) : new Date(),
    deadline: taskData.deadline ? new Date(taskData.deadline) : "",
    status: initialPercent === 100 ? "COMPLETED" : (initialPercent > 0 ? "IN_PROGRESS" : "NOT_STARTED"),
    completionPercent: initialPercent,
    departmentAssignments: deptAssignments.length > 0 ? JSON.stringify(deptAssignments) : "",
    remarks: taskData.remarks || "",
    rejectionRemarks: "",
    completionDate: "",
    driveLink: taskData.driveLink || "",
    isAutoGenerated: String(taskData.isAutoGenerated).toUpperCase() === "TRUE" ? "TRUE" : "FALSE",
    sourceTemplateId: taskData.sourceTemplateId || ""
  };

  var insertedTask = tasksRepo.insert(newTask);
  
  // Send email notifications to all assigned operators across departments
  if (deptAssignments.length > 0) {
    for (var i = 0; i < deptAssignments.length; i++) {
      var sub = deptAssignments[i];
      if (sub.assignedTo) {
        sendNotification("TASK_ASSIGNED", insertedTask, sub.assignedTo, {
          teamName: sub.teamName || "",
          operatorName: sub.assigneeName || ""
        });
      }
    }
  } else if (insertedTask.assignedTo) {
    sendNotification("TASK_ASSIGNED", insertedTask, insertedTask.assignedTo);
  }
  
  // Log task updates history entry
  logTaskUpdate(
    insertedTask.taskId,
    creatorUserId || "SYSTEM",
    "",
    "NOT_STARTED",
    "",
    0,
    taskData.remarks || "Task created with multi-department assignments."
  );

  return insertedTask;
}

/**
 * Updates a task. Handles individual department sub-progress updates and overall aggregation.
 * @param {string} taskId - Unique ID of the task to update
 * @param {Object} taskData - Fields to update
 * @param {string} operatorUserId - User ID of the updating operator
 * @returns {Object} The updated task record
 */
function handleUpdateTask(taskId, taskData, operatorUserId) {
  if (!taskId || !taskData) {
    throw new Error("Missing task ID or update payload.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var existingTask = tasksRepo.getById(taskId);
  if (!existingTask) {
    throw new Error("Task not found with ID: " + taskId);
  }

  var updateFields = {};
  if (taskData.hasOwnProperty("taskTitle")) updateFields.taskTitle = taskData.taskTitle;
  if (taskData.hasOwnProperty("taskDescription")) updateFields.taskDescription = taskData.taskDescription;
  if (taskData.hasOwnProperty("teamId")) updateFields.teamId = taskData.teamId;
  if (taskData.hasOwnProperty("priority")) updateFields.priority = taskData.priority;
  if (taskData.hasOwnProperty("driveLink")) updateFields.driveLink = taskData.driveLink;
  if (taskData.hasOwnProperty("verifierId")) updateFields.verifierId = taskData.verifierId;
  if (taskData.hasOwnProperty("remarks")) updateFields.remarks = taskData.remarks;
  if (taskData.hasOwnProperty("rejectionRemarks")) updateFields.rejectionRemarks = taskData.rejectionRemarks;

  // Multi-department sub-assignment handling
  var currentDeptAssignments = [];
  if (existingTask.departmentAssignments) {
    try {
      currentDeptAssignments = JSON.parse(existingTask.departmentAssignments);
    } catch (e) {
      currentDeptAssignments = [];
    }
  }

  // Check if an individual operator is updating their specific department's sub-progress
  if (taskData.updateSubAssignment) {
    var subUpdate = taskData.updateSubAssignment; // { teamId, progress, status, remarks }
    var matched = false;
    for (var d = 0; d < currentDeptAssignments.length; d++) {
      if ((subUpdate.teamId && currentDeptAssignments[d].teamId === subUpdate.teamId) ||
          (subUpdate.assignedTo && currentDeptAssignments[d].assignedTo === subUpdate.assignedTo) ||
          (currentDeptAssignments[d].assignedTo === operatorUserId)) {
        if (subUpdate.progress !== undefined) currentDeptAssignments[d].progress = Number(subUpdate.progress);
        if (subUpdate.status) currentDeptAssignments[d].status = subUpdate.status;
        if (subUpdate.remarks) currentDeptAssignments[d].remarks = subUpdate.remarks;
        currentDeptAssignments[d].lastUpdated = new Date().toISOString();
        matched = true;
        break;
      }
    }
    if (matched) {
      updateFields.departmentAssignments = JSON.stringify(currentDeptAssignments);
    }
  } else if (taskData.hasOwnProperty("departmentAssignments")) {
    var newAssignments = [];
    if (typeof taskData.departmentAssignments === "string") {
      try { newAssignments = JSON.parse(taskData.departmentAssignments); } catch (e) {}
    } else if (Array.isArray(taskData.departmentAssignments)) {
      newAssignments = taskData.departmentAssignments;
    }

    if (newAssignments.length > 0 && currentDeptAssignments.length > 0) {
      // Check user role and team
      var userRole = "";
      var userTeam = "";
      try {
        var uRepo = new SheetRepository("02_Users", "USR", "userId");
        var uRec = uRepo.getById(operatorUserId);
        if (uRec) {
          userRole = String(uRec.role || "").toUpperCase();
          userTeam = uRec.teamId || "";
        }
      } catch (e) {}

      var isExec = userRole === "ADMIN" || userRole === "PRESIDENT" || userRole === "VP";

      // Only apply sub-assignment changes that the operator is authorized to edit
      for (var d = 0; d < currentDeptAssignments.length; d++) {
        var existingSub = currentDeptAssignments[d];
        var incomingSub = null;
        for (var n = 0; n < newAssignments.length; n++) {
          if ((newAssignments[n].teamId && newAssignments[n].teamId === existingSub.teamId) ||
              (newAssignments[n].assignedTo && newAssignments[n].assignedTo === existingSub.assignedTo)) {
            incomingSub = newAssignments[n];
            break;
          }
        }

        if (incomingSub) {
          var canEditThisSub = isExec || (userRole === "LEAD" && existingSub.teamId === userTeam) || (existingSub.assignedTo === operatorUserId);
          if (canEditThisSub) {
            if (incomingSub.progress !== undefined) existingSub.progress = Number(incomingSub.progress);
            if (incomingSub.status) existingSub.status = incomingSub.status;
            if (incomingSub.remarks !== undefined) existingSub.remarks = incomingSub.remarks;
            existingSub.lastUpdated = new Date().toISOString();
          }
        }
      }
      updateFields.departmentAssignments = JSON.stringify(currentDeptAssignments);
    } else {
      currentDeptAssignments = newAssignments;
      updateFields.departmentAssignments = JSON.stringify(currentDeptAssignments);
    }
  }

  // Calculate aggregate progress and status from sub-assignments if present
  var targetStatus = taskData.status ? taskData.status.toUpperCase() : existingTask.status;
  var targetPercent = taskData.completionPercent !== undefined ? Number(taskData.completionPercent) : Number(existingTask.completionPercent);

  if (currentDeptAssignments.length > 0) {
    var totalSub = currentDeptAssignments.reduce(function(acc, curr) { return acc + (Number(curr.progress) || 0); }, 0);
    targetPercent = Math.round(totalSub / currentDeptAssignments.length);

    var allCompleted = currentDeptAssignments.every(function(s) { return s.status === "COMPLETED" || s.progress === 100; });
    var anyVerify = currentDeptAssignments.some(function(s) { return s.status === "VERIFY"; });
    var anyBlocked = currentDeptAssignments.some(function(s) { return s.status === "BLOCKED"; });
    var allNotStarted = currentDeptAssignments.every(function(s) { return s.progress === 0 && (s.status === "NOT_STARTED" || !s.status); });

    if (allCompleted) {
      targetStatus = "COMPLETED";
      targetPercent = 100;
    } else if (anyVerify) {
      targetStatus = "VERIFY";
    } else if (anyBlocked) {
      targetStatus = "BLOCKED";
    } else if (allNotStarted) {
      targetStatus = "NOT_STARTED";
    } else {
      targetStatus = "IN_PROGRESS";
    }
  } else {
    // Standard single-assignee status consistency
    if (taskData.hasOwnProperty("status") && !taskData.hasOwnProperty("completionPercent")) {
      if (targetStatus === "COMPLETED" || targetStatus === "VERIFY") {
        targetPercent = 100;
      } else if (targetStatus === "NOT_STARTED") {
        targetPercent = 0;
      }
    } else if (!taskData.hasOwnProperty("status") && taskData.hasOwnProperty("completionPercent")) {
      if (targetPercent === 100) {
        if (existingTask.status !== "VERIFY" && existingTask.status !== "COMPLETED") {
          targetStatus = "COMPLETED";
        }
      } else if (existingTask.status === "COMPLETED" && targetPercent < 100) {
        targetStatus = targetPercent === 0 ? "NOT_STARTED" : "IN_PROGRESS";
      }
    }
  }

  updateFields.status = targetStatus;
  updateFields.completionPercent = targetPercent;

  // Manage completionDate
  if (targetStatus === "COMPLETED") {
    updateFields.completionDate = existingTask.completionDate ? existingTask.completionDate : new Date();
  } else if (targetStatus !== "VERIFY") {
    updateFields.completionDate = "";
  }

  // Manage deadline changes
  if (taskData.hasOwnProperty("deadline")) {
    var newDeadline = taskData.deadline ? new Date(taskData.deadline) : "";
    var oldDeadlineStr = existingTask.deadline ? String(new Date(existingTask.deadline)) : "";
    var newDeadlineStr = newDeadline ? String(newDeadline) : "";
    
    if (oldDeadlineStr !== newDeadlineStr) {
      updateFields.deadline = newDeadline;
      logAudit(
        operatorUserId,
        "tasks.updateDeadline",
        "Tasks",
        taskId,
        oldDeadlineStr,
        newDeadlineStr,
        "SUCCESS"
      );
    }
  }

  // Manage Task Reassignment
  var isReassigned = false;
  if (taskData.hasOwnProperty("assignedTo") && taskData.assignedTo !== existingTask.assignedTo) {
    updateFields.assignedTo = taskData.assignedTo;
    isReassigned = true;
    logAudit(
      operatorUserId,
      "tasks.assign",
      "Tasks",
      taskId,
      existingTask.assignedTo || "UNASSIGNED",
      taskData.assignedTo || "UNASSIGNED",
      "SUCCESS"
    );
  }

  // Task History Updates Log
  var statusChanged = targetStatus !== existingTask.status;
  var percentChanged = targetPercent !== Number(existingTask.completionPercent);
  
  if (statusChanged || percentChanged || isReassigned) {
    logTaskUpdate(
      taskId,
      operatorUserId,
      existingTask.status,
      targetStatus,
      existingTask.completionPercent,
      targetPercent,
      taskData.remarks || "Task progress updated across departments."
    );
  }

  // Perform sheet update
  var updated = tasksRepo.update(taskId, updateFields);

  // Trigger notifications
  if (isReassigned && updated.assignedTo) {
    sendNotification("TASK_REASSIGNED", updated, updated.assignedTo);
  } else if (statusChanged) {
    if (targetStatus === "BLOCKED") {
      sendNotification("TASK_BLOCKED", updated, updated.assignedBy || updated.verifierId, {
        blockReason: taskData.remarks || "Marked as blocked by department team member."
      });
    } else if (targetStatus === "VERIFY") {
      sendNotification("TASK_READY_FOR_VERIFICATION", updated, updated.verifierId || updated.assignedBy, {
        remarks: taskData.remarks || ""
      });
    } else if (targetStatus === "COMPLETED" && existingTask.status === "VERIFY") {
      sendNotification("TASK_VERIFIED", updated, updated.assignedTo);
    } else if (targetStatus === "REJECTED") {
      sendNotification("TASK_REJECTED", updated, updated.assignedTo, {
        rejectionRemark: taskData.rejectionRemarks || taskData.remarks || ""
      });
    }
  }

  return updated;
}

/**
 * Task owner submits task for verification by leadership.
 */
function handleTaskSubmitForVerification(taskId, verifierId, remarks, operatorUserId) {
  if (!taskId) throw new Error("Missing task ID.");

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = tasksRepo.getById(taskId);
  if (!task) throw new Error("Task not found with ID: " + taskId);

  var payload = {
    status: "VERIFY",
    completionPercent: 100,
    remarks: remarks || "Submitted for verification."
  };
  if (verifierId) {
    payload.verifierId = verifierId;
  }

  return handleUpdateTask(taskId, payload, operatorUserId);
}

/**
 * Verifier approves and verifies the task (marks as COMPLETED / VERIFIED).
 */
function handleTaskVerify(taskId, remarks, operatorUserId) {
  if (!taskId) throw new Error("Missing task ID.");

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = tasksRepo.getById(taskId);
  if (!task) throw new Error("Task not found with ID: " + taskId);

  var verifierUser = resolveNotificationRecipient(operatorUserId);
  var verifierName = verifierUser ? verifierUser.name : "Verifier";

  var updated = handleUpdateTask(taskId, {
    status: "COMPLETED",
    completionPercent: 100,
    remarks: remarks || "Task verified and approved by " + verifierName
  }, operatorUserId);

  logAudit(
    operatorUserId,
    "tasks.verify",
    "Tasks",
    taskId,
    task.status,
    "COMPLETED",
    "SUCCESS"
  );

  return updated;
}

/**
 * Verifier rejects the task and requests changes.
 */
function handleTaskReject(taskId, remarks, operatorUserId) {
  if (!taskId) throw new Error("Missing task ID.");
  if (!remarks) throw new Error("Rejection remarks / feedback reason is required.");

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = tasksRepo.getById(taskId);
  if (!task) throw new Error("Task not found with ID: " + taskId);

  var verifierUser = resolveNotificationRecipient(operatorUserId);
  var verifierName = verifierUser ? verifierUser.name : "Verifier";

  var updated = handleUpdateTask(taskId, {
    status: "REJECTED",
    rejectionRemarks: remarks,
    remarks: "Changes requested by " + verifierName + ": " + remarks
  }, operatorUserId);

  logAudit(
    operatorUserId,
    "tasks.reject",
    "Tasks",
    taskId,
    task.status,
    "REJECTED",
    "SUCCESS"
  );

  return updated;
}

/**
 * Updates a task's status directly.
 */
function handleUpdateTaskStatus(taskId, status, remarks, operatorUserId) {
  if (!status) {
    throw new Error("Status is required.");
  }
  var stat = String(status || '').toUpperCase();
  var proposedPercent = undefined;
  if (stat === "COMPLETED" || stat === "VERIFY") proposedPercent = 100;
  if (stat === "NOT_STARTED") proposedPercent = 0;

  return handleUpdateTask(taskId, {
    status: stat,
    completionPercent: proposedPercent,
    remarks: remarks
  }, operatorUserId);
}

/**
 * Updates a task's completion percent directly.
 */
function handleUpdateTaskProgress(taskId, completionPercent, remarks, operatorUserId) {
  if (completionPercent === undefined || isNaN(Number(completionPercent))) {
    throw new Error("Valid completionPercent is required.");
  }
  var percent = Number(completionPercent);
  var proposedStatus = undefined;
  if (percent === 100) {
    proposedStatus = "COMPLETED";
  } else if (percent === 0) {
    proposedStatus = "NOT_STARTED";
  }

  return handleUpdateTask(taskId, {
    status: proposedStatus,
    completionPercent: percent,
    remarks: remarks
  }, operatorUserId);
}

/**
 * Calculates the target user's workload indicators.
 */
function handleGetUserWorkload(targetUserId) {
  if (!targetUserId) {
    throw new Error("Missing target user ID.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var userTasks = tasksRepo.find({ assignedTo: targetUserId });
  
  var activeCount = 0;
  for (var i = 0; i < userTasks.length; i++) {
    var status = String(userTasks[i].status || '').toUpperCase();
    if (["NOT_STARTED", "IN_PROGRESS", "DELAYED", "BLOCKED", "VERIFY", "REJECTED"].indexOf(status) !== -1) {
      activeCount++;
    }
  }

  var settingsRepo = new SheetRepository("00_Settings", null, "settingKey");
  var normalMaxVal = settingsRepo.getById("WORKLOAD_NORMAL_MAX");
  var highMaxVal = settingsRepo.getById("WORKLOAD_HIGH_MAX");
  
  var normalMax = normalMaxVal ? parseInt(normalMaxVal.settingValue, 10) : 5;
  var highMax = highMaxVal ? parseInt(highMaxVal.settingValue, 10) : 10;

  var workloadState = "NORMAL";
  if (activeCount > normalMax && activeCount <= highMax) {
    workloadState = "HIGH";
  } else if (activeCount > highMax) {
    workloadState = "OVERLOADED";
  }

  return {
    activeCount: activeCount,
    workloadState: workloadState
  };
}

/**
 * Deletes / cancels a task.
 */
function handleDeleteTask(taskId, operatorUserId) {
  if (!taskId) throw new Error("Missing task ID.");
  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var existingTask = tasksRepo.getById(taskId);
  if (!existingTask) throw new Error("Task not found with ID: " + taskId);

  var deleted = tasksRepo.delete(taskId);
  logTaskUpdate(taskId, operatorUserId || "SYSTEM", existingTask.status, "CANCELLED", existingTask.completionPercent, 0, "Task deleted/cancelled.");
  logAudit(operatorUserId, "tasks.delete", "Tasks", taskId, existingTask, deleted, "SUCCESS");
  return deleted;
}

/**
 * Internal helper to write update entries to the 05_Task_Updates sheet.
 */
function logTaskUpdate(taskId, operatorUserId, previousStatus, newStatus, previousCompletion, newCompletion, remarks) {
  try {
    var updatesRepo = new SheetRepository("05_Task_Updates", "UPD", "updateId");
    updatesRepo.insert({
      taskId: taskId,
      updatedBy: operatorUserId || "SYSTEM",
      previousStatus: previousStatus || "",
      newStatus: newStatus || "",
      previousCompletion: previousCompletion !== "" ? Number(previousCompletion) : "",
      newCompletion: newCompletion !== "" ? Number(newCompletion) : "",
      remarks: remarks || ""
    });
  } catch (err) {
    Logger.log("Failed to write task update log: " + err.toString());
  }
}
