// TasksHandler.gs — Core handlers for Tasks management (04_Tasks sheet).

/**
 * Returns all active (non-cancelled) tasks.
 * @returns {Array<Object>} List of active tasks
 */
function handleListTasks() {
  var repo = new SheetRepository("04_Tasks", "TSK", "taskId");
  return repo.getAll();
}

/**
 * Retrieves details for a single task by ID.
 * @param {string} taskId - Unique ID of the task
 * @returns {Object} The task details
 */
function handleGetTask(taskId) {
  if (!taskId) {
    throw new Error("Missing task ID.");
  }
  var repo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var task = repo.getById(taskId);
  if (!task) {
    throw new Error("Task not found with ID: " + taskId);
  }
  return task;
}

/**
 * Creates a new task. Enforces that new tasks start as NOT_STARTED / 0%.
 * @param {Object} taskData - Task parameter payload
 * @param {string} creatorUserId - User ID of the creator
 * @returns {Object} The newly created task record
 */
function handleCreateTask(taskData, creatorUserId) {
  if (!taskData || !taskData.taskTitle) {
    throw new Error("Invalid payload: taskTitle is required.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");

  var newTask = {
    eventId: taskData.eventId || "",
    projectId: taskData.projectId || "",
    taskTitle: taskData.taskTitle,
    taskDescription: taskData.taskDescription || "",
    teamId: taskData.teamId || "",
    assignedTo: taskData.assignedTo || "",
    assignedBy: creatorUserId || "",
    priority: taskData.priority || "MEDIUM",
    startDate: taskData.startDate ? new Date(taskData.startDate) : new Date(),
    deadline: taskData.deadline ? new Date(taskData.deadline) : "",
    status: "NOT_STARTED", // Enforce initial status rules
    completionPercent: 0,   // Enforce initial progress rules
    remarks: taskData.remarks || "",
    completionDate: "",
    driveLink: taskData.driveLink || "",
    isAutoGenerated: String(taskData.isAutoGenerated).toUpperCase() === "TRUE" ? "TRUE" : "FALSE",
    sourceTemplateId: taskData.sourceTemplateId || ""
  };

  var insertedTask = tasksRepo.insert(newTask);
  
  // Send email notification to the assignee
  sendTaskEmailNotification(insertedTask);
  
  // Log task updates history entry
  logTaskUpdate(
    insertedTask.taskId,
    creatorUserId || "SYSTEM",
    "",
    "NOT_STARTED",
    "",
    0,
    taskData.remarks || "Task created."
  );

  return insertedTask;
}

/**
 * Updates a task. Enforces status consistency, history updates, and audit logging.
 * @param {string} taskId - Unique ID of the task to update
 * @param {Object} taskData - Fields to update
 * @param {string} operatorUserId - User ID of the updating operator
 * @returns {Object} The updated task record
 */
function handleUpdateTask(taskId, taskData, operatorUserId) {
  if (!taskId || !taskData) {
    throw new Error("Missing task ID or update payload.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var existingTask = tasksRepo.getById(taskId);
  if (!existingTask) {
    throw new Error("Task not found with ID: " + taskId);
  }

  var updateFields = {};
  if (taskData.hasOwnProperty("taskTitle")) updateFields.taskTitle = taskData.taskTitle;
  if (taskData.hasOwnProperty("taskDescription")) updateFields.taskDescription = taskData.taskDescription;
  if (taskData.hasOwnProperty("teamId")) updateFields.teamId = taskData.teamId;
  if (taskData.hasOwnProperty("priority")) updateFields.priority = taskData.priority;
  if (taskData.hasOwnProperty("driveLink")) updateFields.driveLink = taskData.driveLink;

  // 1. Enforce Status and Progress consistency rules (PRD §14)
  var targetStatus = taskData.status ? taskData.status.toUpperCase() : existingTask.status;
  var targetPercent = taskData.completionPercent !== undefined ? Number(taskData.completionPercent) : Number(existingTask.completionPercent);

  Logger.log("UpdateTask DEBUG: taskId=" + taskId + ", taskData=" + JSON.stringify(taskData) + ", existingTask.status=" + existingTask.status + ", existingTask.completionPercent=" + existingTask.completionPercent);

  // If both status and completionPercent are supplied, validate them strictly first
  if (taskData.hasOwnProperty("status") && taskData.hasOwnProperty("completionPercent")) {
    var s = taskData.status.toUpperCase();
    var p = Number(taskData.completionPercent);
    if (s === "COMPLETED" && p !== 100) {
      throw new Error("A completed task must have 100% completion percent.");
    }
    if (p === 100 && s !== "COMPLETED") {
      throw new Error("A task at 100% completion must be in COMPLETED status.");
    }
    if (s === "NOT_STARTED" && p !== 0) {
      throw new Error("A task in NOT_STARTED status must have 0% completion percent.");
    }
  }

  // Automatic adjustment if only one field is updated
  if (taskData.hasOwnProperty("status") && !taskData.hasOwnProperty("completionPercent")) {
    if (targetStatus === "COMPLETED") {
      targetPercent = 100;
    } else if (targetStatus === "NOT_STARTED") {
      targetPercent = 0;
    }
  } else if (!taskData.hasOwnProperty("status") && taskData.hasOwnProperty("completionPercent")) {
    if (targetPercent === 100) {
      targetStatus = "COMPLETED";
    } else if (existingTask.status === "COMPLETED" && targetPercent < 100) {
      if (targetPercent === 0) {
        targetStatus = "NOT_STARTED";
      } else {
        targetStatus = "IN_PROGRESS";
      }
    }
  }

  // Final sanity validation checks
  if (targetStatus === "COMPLETED" && targetPercent !== 100) {
    throw new Error("A completed task must have 100% completion percent.");
  }
  if (targetPercent === 100 && targetStatus !== "COMPLETED") {
    throw new Error("A task at 100% completion must be in COMPLETED status.");
  }
  if (targetPercent === 0 && targetStatus === "COMPLETED") {
    throw new Error("A task at 0% completion cannot be in COMPLETED status.");
  }

  updateFields.status = targetStatus;
  updateFields.completionPercent = targetPercent;

  // Manage completionDate
  if (targetStatus === "COMPLETED") {
    updateFields.completionDate = existingTask.completionDate ? existingTask.completionDate : new Date();
  } else {
    updateFields.completionDate = "";
  }

  // 2. Deadline Changes (Enforce security logs)
  if (taskData.hasOwnProperty("deadline")) {
    var newDeadline = taskData.deadline ? new Date(taskData.deadline) : "";
    var oldDeadlineStr = existingTask.deadline ? String(new Date(existingTask.deadline)) : "";
    var newDeadlineStr = newDeadline ? String(newDeadline) : "";
    
    if (oldDeadlineStr !== newDeadlineStr) {
      updateFields.deadline = newDeadline;
      logAudit(
        operatorUserId,
        "tasks.updateDeadline",
        "Tasks",
        taskId,
        oldDeadlineStr,
        newDeadlineStr,
        "SUCCESS"
      );
    }
  }

  // 3. Task Reassignment (Enforce security logs)
  if (taskData.hasOwnProperty("assignedTo") && taskData.assignedTo !== existingTask.assignedTo) {
    updateFields.assignedTo = taskData.assignedTo;
    logAudit(
      operatorUserId,
      "tasks.assign",
      "Tasks",
      taskId,
      existingTask.assignedTo || "UNASSIGNED",
      taskData.assignedTo || "UNASSIGNED",
      "SUCCESS"
    );
  }

  // 4. Task History Updates Log (PRD §57)
  var statusChanged = targetStatus !== existingTask.status;
  var percentChanged = targetPercent !== Number(existingTask.completionPercent);
  
  if (statusChanged || percentChanged || (taskData.hasOwnProperty("assignedTo") && taskData.assignedTo !== existingTask.assignedTo)) {
    logTaskUpdate(
      taskId,
      operatorUserId,
      existingTask.status,
      targetStatus,
      existingTask.completionPercent,
      targetPercent,
      taskData.remarks || "Task details updated."
    );
  }

  // Perform update
  var updated = tasksRepo.update(taskId, updateFields);
  if (updateFields.hasOwnProperty("assignedTo")) {
    sendTaskEmailNotification(updated);
  }
  return updated;
}

/**
 * Updates a task's status directly.
 */
function handleUpdateTaskStatus(taskId, status, remarks, operatorUserId) {
  if (!status) {
    throw new Error("Status is required.");
  }
  var stat = status.toUpperCase();
  var proposedPercent = undefined;
  if (stat === "COMPLETED") proposedPercent = 100;
  if (stat === "NOT_STARTED") proposedPercent = 0;

  return handleUpdateTask(taskId, {
    status: stat,
    completionPercent: proposedPercent,
    remarks: remarks
  }, operatorUserId);
}

/**
 * Updates a task's completion percent directly.
 */
function handleUpdateTaskProgress(taskId, completionPercent, remarks, operatorUserId) {
  if (completionPercent === undefined || isNaN(Number(completionPercent))) {
    throw new Error("Valid completionPercent is required.");
  }
  var percent = Number(completionPercent);
  var proposedStatus = undefined;
  if (percent === 100) {
    proposedStatus = "COMPLETED";
  } else if (percent === 0) {
    // If resetting to 0%, revert status if it was completed
    proposedStatus = "NOT_STARTED";
  }

  return handleUpdateTask(taskId, {
    status: proposedStatus,
    completionPercent: percent,
    remarks: remarks
  }, operatorUserId);
}

/**
 * Calculates the target user's workload indicators.
 * @param {string} targetUserId - Unique ID of the target user
 * @returns {Object} Workload information
 */
function handleGetUserWorkload(targetUserId) {
  if (!targetUserId) {
    throw new Error("Missing target user ID.");
  }

  var tasksRepo = new SheetRepository("04_Tasks", "TSK", "taskId");
  var userTasks = tasksRepo.find({ assignedTo: targetUserId });
  
  var activeCount = 0;
  for (var i = 0; i < userTasks.length; i++) {
    var status = userTasks[i].status ? userTasks[i].status.toUpperCase() : "";
    // Active tasks = NOT_STARTED, IN_PROGRESS, DELAYED, BLOCKED
    if (["NOT_STARTED", "IN_PROGRESS", "DELAYED", "BLOCKED"].indexOf(status) !== -1) {
      activeCount++;
    }
  }

  var settingsRepo = new SheetRepository("00_Settings", null, "settingKey");
  var normalMaxVal = settingsRepo.getById("WORKLOAD_NORMAL_MAX");
  var highMaxVal = settingsRepo.getById("WORKLOAD_HIGH_MAX");
  
  var normalMax = normalMaxVal ? parseInt(normalMaxVal.settingValue, 10) : 5;
  var highMax = highMaxVal ? parseInt(highMaxVal.settingValue, 10) : 10;

  var workloadState = "NORMAL";
  if (activeCount > normalMax && activeCount <= highMax) {
    workloadState = "HIGH";
  } else if (activeCount > highMax) {
    workloadState = "OVERLOADED";
  }

  return {
    activeCount: activeCount,
    workloadState: workloadState
  };
}

/**
 * Internal helper to write update entries to the 05_Task_Updates sheet.
 */
function logTaskUpdate(taskId, operatorUserId, previousStatus, newStatus, previousCompletion, newCompletion, remarks) {
  try {
    var updatesRepo = new SheetRepository("05_Task_Updates", "UPD", "updateId");
    updatesRepo.insert({
      taskId: taskId,
      updatedBy: operatorUserId || "SYSTEM",
      previousStatus: previousStatus || "",
      newStatus: newStatus || "",
      previousCompletion: previousCompletion !== "" ? Number(previousCompletion) : "",
      newCompletion: newCompletion !== "" ? Number(newCompletion) : "",
      remarks: remarks || ""
    });
  } catch (err) {
    Logger.log("Failed to write task update log: " + err.toString());
  }
}

/**
 * Transnational email dispatcher for task assignments.
 */
function sendTaskEmailNotification(taskRecord) {
  if (!taskRecord || !taskRecord.assignedTo) return;

  try {
    var usersRepo = new SheetRepository("01_Users", "USR", "userId");
    var userRecord = null;

    if (taskRecord.assignedTo.indexOf("USR-") === 0) {
      userRecord = usersRepo.getById(taskRecord.assignedTo);
    } else {
      var matched = usersRepo.find({ firebaseUid: taskRecord.assignedTo });
      if (matched.length > 0) {
        userRecord = matched[0];
      }
    }

    if (userRecord && userRecord.email) {
      var subject = "NEXUS CRM: New Task Assignment - " + taskRecord.taskTitle;
      var body = "Hi " + userRecord.name + ",\n\n" +
                 "You have been assigned a new task on the NEXUS CRM portal.\n\n" +
                 "Task Details:\n" +
                 "- Title: " + taskRecord.taskTitle + "\n" +
                 "- Description: " + (taskRecord.taskDescription || "No description") + "\n" +
                 "- Priority: " + (taskRecord.priority || "MEDIUM") + "\n" +
                 "- Deadline: " + (taskRecord.deadline ? new Date(taskRecord.deadline).toLocaleDateString() : "No deadline") + "\n\n" +
                 "Please log in to the portal at http://localhost:5173 to review and update your progress.\n\n" +
                 "Best regards,\n" +
                 "NEXUS Core Team";

      MailApp.sendEmail(userRecord.email, subject, body);
      Logger.log("Email notification successfully sent to: " + userRecord.email);
    }
  } catch (err) {
    Logger.log("Failed to send task email notification: " + err.toString());
  }
}
